zigpy/zigpy

zigpy/zcl/clusters/general.py

This fixes an issue where we could get this error: 
`OSError: [Errno 22] Invalid argument`.

Fixed problem with using 0 in datetime

---

zigpy/types/basic.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/foundation.py

According to ZigBee Cluster Library Specification Revision 6 Draft Version 1.0. The Fan Control cluster (0x0202) has 2 attributes both are enum8.
Currently zigpy treats all enums as unit8_t & unit16_t, which causes the following error when those attributes are written:
`[[<WriteAttributesStatusRecord status=Status.INVALID_DATA_TYPE attrid=0>]]`
This change has been verified to work on the following fan receiver:
https://www.homedepot.com/p/Hampton-Bay-Universal-Wink-Enabled-White-Ceiling-Fan-Premier-Remote-Control-99432/206591100.
This change is based on:
https://github.com/zigpy/bellows/pull/71

Fix fan control attributes to enums.

---

zigpy/device.py

this patch uses the source endpoint in a incoming packet to assign the packet to right endpoint.
example: getting attribute reports from device , endpoint 10, cluster 0x702, send to endpoint 1
current code -> incoming packet from source-endpoint 10, cluster x, destination-endpoint 1 -> unknown cluster 0x702 for endpoint 1.
with this patch the message goes to the correct endpoint 10.
this shows only when the device uses an endpoint != 1, why it may have not come to attention before

bug in frame handler for src endpoint

---

zigpy/device.py
zigpy/endpoint.py
zigpy/zcl/__init__.py

Allow for commands to disable waiting for replies. This can be used to workaround devices that improperly implement the zigbee zha spec
Original:
According to ZigBee Cluster Library SpecificationRevision 6 Draft Version 1.0, Section 2.5.12.2 "When Generated", zigbee is not required to issue an explicit reply. If the initiating request is expecting a Default Response then any message sent with the same Transaction sequence number can act as a reply. The implementation to track what counts as a stand-in for a Default Response would be nontrivial.
This change fixes the behavior for the most common case of sending commands by setting expect_reply=False for all commands. This will most likely break other use cases where a command requires a response (ie. the Get Alarm request). In the longer …

Bubble expect_reply parameter up to clusters (was:Stop expecting replies for commands.)

---

zigpy/zcl/clusters/general.py

I was having trouble configuring reporting for the present_value attribute, and realized that it was defined as Single rather than Bool type (so the command was expecting a minimum change). I'm fairly new to creating pull requests some I'm not sure if you would want to pull to the master or what you want to do about versioning. Let me know if I need to change anything.

Fixed incorrect attribute types in BinaryOutput and BinaryInput clusters

---

tests/test_endpoint.py
zigpy/endpoint.py

packets to zll devices should use the  zha profile id in frames if the cluster is not 0x1000 
See https://www.silabs.com/documents/public/user-guides/UG103.9.pdf section 3.1
This fixes issue #17 and also other bulbs with same behavior. 
Second try with  a new  branch

Fix zll profile in zha cluster2

---

zigpy/application.py
zigpy/device.py

This provides a better interface for device to signal to the application that it is initialized, and allows the application to perform any operations which may be useful, other than beginning persistence.

Add device_initialized to application

---

tests/test_application.py
tests/test_device.py
tests/test_zcl.py
tests/test_zdo.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/zcl/__init__.py
zigpy/zdo/__init__.py

To allow custom devices with custom deserialization strategies, we can't rely on a global registry.

Deserialize using device/endpoint/cluster object tree

---

zigpy/types/basic.py
zigpy/zcl/clusters/measurement.py
zigpy/zcl/foundation.py

According to ZigBee Cluster Library Specification Revision 6 Draft Version 1.0 the OccupancySensing cluster (0x0406) has attribute 'occupancy' of bitmap8 type. Currently zigpy treats this attribute as uint8 and when I try to configure reporting I get status 141 -- Invalid data type:
```
2018-05-22 20:49:08 DEBUG (MainThread) [homeassistant.components.binary_sensor.zha] Configured reporting for attr_id 0 on 00:0d:6f:00:0e:38:22:dc-1030: 300/900/1: [[<ConfigureReportingResponseRecord status=141 direction=0 attrid=0>]]
```
if using bitmap8 data type (id 0x18) then report configuration succeeds:
```
2018-05-22 21:17:10 DEBUG (MainThread) [homeassistant.components.binary_sensor.zha] Configured reporting for attr_id 0 on 00:0d:6f:00:0e:38:22:dc-1030: 300/900/1: …
```

Add bitmap type for 'occupancy' attribute of OccupancySensing  cluster.

---

zigpy/profiles/zha.py
zigpy/zcl/clusters/closures.py

This allows to communicate with the clusters of ZHA window covering devices (like the ubisys shutter control J1) and fixes a few minor typos / issues within these cluster specifications.

support zha window covering devices

---

zigpy/zdo/__init__.py

Per definition of [Mgmt_leave_req](https://github.com/zigpy/zigpy/blob/a452c1c61778b116447ab36d1bf7e08b8820ebbf/zigpy/zdo/types.py#L124) of ZDO clusters, Mgmt_leave_req only takes two arguments:
1. device address
2. options
however current implementation also provides an extra parameter which seems to be just a copy'n'paste artifact from the above bind/unbind methods.
Same arguments for Mgmt_leave_req were defined in ZDO specs

cleanup zdo.leave() method and remove unneeded extra parameter from cmd request

---

tests/test_appdb.py
tests/test_endpoint.py
zigpy/appdb.py
zigpy/endpoint.py

This adds manufacturer and model to the endpoint object. The values are initially read on device join while the device should be in a responsive state. They are restored from the attribute cache on restarts. This allows HA to avoid "asking" for them when devices are added because they are already set before the device is given to HA.

add manufacturer and model to endpoint

---

tests/test_quirks.py
zigpy/quirks/__init__.py
zigpy/quirks/kof/__init__.py

The King of Fans ceiling fan receiver does not generate default replies. This module overrides all server commands that do not have a mandatory reply to not expect replies at all.

add a quirk for king of fans zigbee receiver

---

tests/test_appdb.py
tests/test_endpoint.py
zigpy/appdb.py
zigpy/endpoint.py

There're some vendor which don't provide clean manufacturer/model attribute values, eg Stelpro STZB402 thermostat. With #56  it breaks zha component in homeassistant:
```
2018-08-06 20:56:59 DEBUG (MainThread) [zigpy.appdb] Attribute id: 32 value: 28
2018-08-06 20:56:59 DEBUG (MainThread) [zigpy.appdb] Attribute id: 4 value: b'Stelpro\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2018-08-06 20:56:59 DEBUG (MainThread) [zigpy.appdb] Attribute id: 5 value: b'STZB402+\x00\x04\\\x00\\\x00\x00\x00\x00\x00\x07\x07\x00\x00\x00\x00\x00\x07\x07\x00\xde\x15\x00'
2018-08-06 20:56:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component zha
Traceback (most recent call last):
File "/home/lex/lex/src/ac-hass/homeassistant/setup.py", …
```

Strip anything starting with 0x00 in manufacturer/model attributes values

---

tests/test_quirks.py

Currently test_quirks.py fails if a custom endpoint replacement contains a cluster ID registered in "cluster ID range", like a manufacturer cluster ID. For example, a custom device with the following replacement:
```
replacement = {
'endpoints': {
1: {
'input_clusters': [0, 3, 4, 5, 513, 0xff01],
'output_clusters': [0x16, 0xff01]
},
196: {
'input_clusters': [PowerConfiguration]}
}
```
fails with 
```
_______________________________________ test_custom_devices _______________________________________
def test_custom_devices():
for device in zigpy.quirks._DEVICE_REGISTRY:
for profile_id, profile_data in device.signature.items():
assert isinstance(profile_id, int)
assert set(profile_data.keys()) - ALLOWED_SIGNATURE == set()
assert set(device.replacement.keys()) - ALLOWED_REPLACEMENT == set() …
```

update quirks test to handle cluster id ranges

---

tests/test_zcl.py
zigpy/zcl/__init__.py

zcl.Cluster.read_attributes() and zcl.Cluster.write_attribute() methods both accept attributes either as attribute ID or attribute name. This PR makes zcl.Cluster.configure_reporting() to behave the same.

update Cluster.configure_reporiting to accept named attributes

---

zigpy/quirks/__init__.py

Copy (or replace) manufacturer and model attributes to CustomEndpoint. Otherwise those are always 'none' for quirky devices.

Add model/manufacturer attributes to CustomEndpoint

---

tests/test_zcl.py
zigpy/zcl/__init__.py

Support `manufacturer` for `Cluster.configure_reporting()` method.
I've got [SmartThings multipurpose sensor](https://www.samsung.com/us/smart-home/smartthings/sensors/samsung-smartthings-multipurpose-sensor-2018-gp-u999sjvlaaa/), mine being specifically PN IM6001-MPP01 and it reject `configure_reporting()` request for the acceleration manufacturer specific cluster, unless configure_reporting() request uses `manufacturer_id` specific to this vendor.

Support manufacturer id for configure_reporting().

---

zigpy/quirks/smartthings/__init__.py

Implement vendor specific `acceleremoter` cluster for [Smartthings multipurpose sensor](https://www.samsung.com/us/smart-home/smartthings/sensors/samsung-smartthings-multipurpose-sensor-2018-gp-u999sjvlaaa/) Per [Smartthings device handler](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/PROD_2018.09.11/devicetypes/smartthings/smartsense-multi-sensor.src/smartsense-multi-sensor.groovy)  there are multiple vendors for the similar sensor, but I was able only to test with sensor from 'samjin' manufacturer.
Configuring reporting for `0xfc02` cluster requires specific manufacturer_id be supplied with all ZCL requests and this functionality is in #82

Add Smartthings multipurpose sensor quirks.

---

.gitignore
tests/test_application.py
zigpy/application.py

This can be used to request that a remote device (router) allows associations.

Add support for targeted permit

---

README.md

Update README.md to also mention and link to zigpy-deconz
https://github.com/damarco/zigpy-deconz
zigpy-deconz is another library for deCONZ serial protocol
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/158

Update README.md to also mention and link to zigpy-deconz

---

tests/test_application.py
zigpy/application.py

When removing a device, pop it from device registry after issuing ZDO leave request.
Currently we're poping the device too soon, so we never get a proper reply to "ZDO leave req" since device is gone and deserialization is not happening. 
Here's a log, for a few devices being issued a `ZDO leave` request, however when we get an `incomingMessageHandler` with a reply to leave request, we fail to process it, because it comes from an unknown device
```
2019-01-02 17:57:51 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service=remove, service_data=ieee_address=f0:d1:b8:00:00:05:13:93, domain=zha>
2019-01-02 17:57:51 INFO (MainThread) [homeassistant.components.zha] Removing node f0:d1:b8:00:00:05:13:93
2019-01-02 17:57:51 INFO (MainThread) [zigpy.application] …
```

Pop device from registry after ZDO leave request.

---

tests/test_zcl.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py

Add support for ZCL discovery commands:
- Discover Attributes
- Discover Attributes extended
- Discover Commands Received
- Discover Commands Generated

Add ZCL discovery commands.

---

tests/test_endpoint.py
tests/test_quirks.py
tests/test_zcl.py
tox.ini
zigpy/appdb.py
zigpy/quirks/__init__.py
zigpy/quirks/xiaomi/__init__.py

This PR adds support to match on model and manufacturer in quirks signatures, which is necessary for some devices like the Xiaomi Humidity/Temperature sensor. This supersedes #97 which has not been updated in a while. Thanks @NNMavy for the initial PR!

Add support for model and manufacturer in quirks signatures

---

tests/test_application.py
zigpy/application.py

Transition to ControllerApplication shutdown() method. At very least should close the serial port. May perform other "clean up" task depending on radio implementation.

Add ControllerApplication.shutdown() method.

---

tests/test_application.py
zigpy/application.py

Currently `ApplicationController.remove()` suppresses only `DeliveryError` exceptions, however some radios (bellows) may raise `asyncio.TimeoutError` exception instead, which would cause the device not to be removed from the database.

Handle TimeoutError during device removal.

---

README.md

"ConBee II" (a.k.a. "ConBee 2") hardware has just now been released and is confirmed by Dresden-Elektronik employee @manup to be backwards compatible with the deCONZ serial protocol that zigpy-deconz radio module for zigpy utilizes. (He, @manup wrote that "the serial protocol is identical and will be maintained for all devices equally").
FYI; Apparently the new "ConBee II" ZigBee USB dongle/stick features is based on a 32-bit ARM-Cortex-M0 SoC microcontroller (Microchip ATSAMR21E18A) instead of an 8-bit AVR based CMOS microcontroller (Atmel ATmega256RFR2) like the previous version of ConBee and the current RaspBee versions.
- https://shop.dresden-elektronik.de/conbee-2.html
- https://www.dresden-elektronik.de/fileadmin/Downloads/Dokumente/Produkte/11_Phoscon_gateway/Phoscon_ConBee-II_10-20 …

Added the new ConBee II (ConBee 2) to known working Zigbee radios

---

tests/test_device.py
tests/test_zigbee_util.py
zigpy/device.py
zigpy/endpoint.py
zigpy/util.py

Fixes https://github.com/zigpy/zigpy/issues/123
if discovery of any endpoint is not completed, then remove the device and drop it from the db to ensure DB consistency.

Drop the device from DB if not fully discovered.

---

tests/test_appdb.py
tests/test_device.py
tests/test_zdo_types.py
zigpy/appdb.py
zigpy/device.py
zigpy/quirks/__init__.py
zigpy/zdo/types.py

This PR adds ZDO Node Descriptor to Zigpy Device and I'm opening this for further discussion and feedback. 
This is in effort to implement `setExtendedTimeout()` in `bellows` to:
> Tell the stack whether or not the normal interval between retransmissions of a retried unicast message should be increased
by EMBER_INDIRECT_TRANSMISSION_TIMEOUT. The interval needs to be increased when sending to a sleepy node so that the message is not retransmitted until the destination has had time to wake up and poll its parent. The stack will automatically extend the timeout: - For our own sleepy children. - When an address response is received from a parent on behalf of its child. - When an indirect transaction expiry route error is received. - When an end device announcement is received from a sleepy …

Add "node descriptor" to zigpy.device.Device class.

---

tests/test_appdb.py
zigpy/appdb.py
zigpy/endpoint.py
zigpy/zcl/__init__.py

`zigpy.endpoint` still had circular imports as it tried to import `zigpy.appdb`, `zigpy.appdb` tried to import `zigpy.quirks` and `zigpy.quirks` required `zigpy.endpoint.Endpoint`:
```
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zigpy.endpoint
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/lex/lex/src/zigpy/zigpy/endpoint.py", line 4, in <module>
import zigpy.appdb
File "/home/lex/lex/src/zigpy/zigpy/appdb.py", line 7, in <module>
import zigpy.quirks
File "/home/lex/lex/src/zigpy/zigpy/quirks/__init__.py", line 102, in <module>
class CustomEndpoint(zigpy.endpoint.Endpoint):
AttributeError: module 'zigpy' has no attribute 'endpoint'
>>> 
``` …

Fix circular imports and tests task leaking.

---

tests/test_zcl_foundation.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py

Implement `__repr__` method for `zigpy.zcl.foundation.TypeValue` class.
Friendly print attribute names (if avaialble) when an attribute report is received.
Log debug message like
```
2019-04-28 02:45:49 DEBUG (MainThread) [zigpy.zcl] [0x16a3:1:0x0b04] ZCL request 0x000a: [[<Attribute attrid=1285 value=<TypeValue type=uint16_t, value=124>>, <Attribute attrid=1288 value=<TypeValue type=uint16_t, value=0>>, <Attribute attrid=1361 value=<TypeValue type=uint32_t, value=52691>>]]
2019-04-28 02:45:49 DEBUG (MainThread) [zigpy.zcl] [0x16a3:1:0x0b04] Attribute report received: rms_voltage=124, rms_current=0, 1361=52691
```
instead of
```
2019-04-28 00:45:49 DEBUG (MainThread) [zigpy.zcl] [0x16a3:1:0x0b04] ZCL request 0x000a: [[<Attribute attrid=1285 value=<zigpy.zcl.foundation.TypeValue object at …
```

__repr__ for zcl.foundation.TypeValue.

---

tests/test_application.py
tests/test_device.py
tests/test_endpoint.py
tests/test_types.py
tests/test_zdo.py
zigpy/device.py
zigpy/endpoint.py
zigpy/types/named.py
zigpy/zdo/__init__.py
zigpy/zdo/types.py

Implement ZDO commands as enums.
Allow ZDO command invoking by their name.
Improves code readability and gets rid of "magic" numbers in the code.

WIP Implement ZDO commands as enums.

---

tests/test_zigbee_util.py
zigpy/util.py

This is useful when creating a single listener object that subscribes to events from multiple sources. My use case is a global listener for the OTA cluster for every device that automatically downloads and caches firmware files. It's a little unwieldy to create one-off classes to just pass events along with some context:
```Python
class OTAListener:
def __init__(self, cluster, global_listener):
self.cluster = cluster
self.global_listener = global_listener
def cluster_command(self, tsn, command_id, args):
self.global_listener(tsn, command_id, args, self.cluster)
global_listener = MainOTAListener()
for device in devices:
ota_cluster = device.endpoints[0x001].out_clusters[0x0019]
ota_cluster.add_listener(OTAListener(ota_cluster, global_listener))
```
Instead, one could do something like …

Add a `context` parameter to `ListenableMixin.add_listener`

---

zigpy/types/basic.py

Some vendors (I mean Xiaomi) are using `Character String` ZCL data type for sending binary data. Really, Xiaomi? Keep the original bytes data as a `raw` attribute of `CharacterString` class.

`raw` attribute for CharacterString class.

---

tests/test_appdb.py
tests/test_types.py
zigpy/types/basic.py

Using the pattern `int.from_bytes(s[:n], 'little')` doesn't enforce that `s` is at least `n` bytes long (or that `s` is even non-empty). I've added checks to prevent this from happening for I think all of the affected data types.
It might be better to create some helper functions in the future to deal with this (or switch to using `BytesIO` objects).

Prevent slicing and int.from_bytes from allowing invalid deserialization

---

tests/test_zcl.py
tests/test_zcl_clusters.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py

If a device tries to read any Time cluster attribute from coordinator, then the response is never awaited. 
eg here's log of a device (GE45857) requesting local time:
```
2019-05-09 12:32:08 DEBUG (MainThread) [zigpy_xbee.api] _handle_explicit_rx: (00:22:a3:00:00:1b:94:bb, 0x43e8, 1, 10, 1, b'0008000700')
2019-05-09 12:32:08 DEBUG (MainThread) [zigpy.zcl] [0x43e8:1:0x000a] ZCL request 0x0000: [[7]]
/home/lex/lex/src/zigpy/zigpy/zcl/clusters/general.py:351: RuntimeWarning: coroutine 'request' was never awaited
self.write_attributes(data, True)
```
Additionally add support for "local_time" attribute.
Reply with "Status.UNSUPPORTED_ATTRIBUTE" for attributes which we don't support on time cluster.

Run cluster_general_request() response for Time cluster in the loop.

---

tests/test_zcl.py
zigpy/zcl/__init__.py

Don't throw an error if number of args doesn't match schema length.
For certain ZCL commands which include Status code, the number of arguments is variable in case `Status != Status.SUCCESS`, for example per [OTA](http://www.zigbee.org/wp-content/uploads/2014/11/docs-09-5264-23-00zi-zigbee-ota-upgrade-cluster-specification.pdf) `query_next_image` response:
Should include other fields only if `Status == Status.SUCCESS`.  Per additional testing, behavior between devices is different and some devices don't really care and ignore the remaining fields, however some devices do care and they reply with an error, like `Bosch Motion Sensor`:
```
2019-05-09 01:45:14 DEBUG (MainThread) [bellows.ezsp] Application frame 69 (incomingMessageHandler) received: b'00040119000501400d00007cffbc7135fff …
```

Relax schema check for ZCL replies.

---

tests/test_appdb.py
tests/test_device.py
tests/test_group.py
zigpy/appdb.py
zigpy/application.py
zigpy/device.py
zigpy/group.py
zigpy/types/named.py
zigpy/zcl/clusters/general.py

**Group Management Framework**
* ApplicationController contains `groups` property (`Groups` class) which is a dict of `Group`'s instances
* each `Group` instance is a dict containing member devices (keyed on `IEEE` ) and have the following properties
* `group_id` -- group ID
* `name` -- group name
A Zigpy Device can be added to a group by calling the async `zigpy.device.Device.add_to_group(group_id, group_name)` method.  A Zigpy Device can be removed from a group by calling the async `zigpy.device.Device.remove_from_group(group_id)` method. Each device has a `member_of` dict, keyed by group_id of which device is member of.
My idea is to add radios as a Zigpy device and each radio could implement its own `add_to_group()`/`remove_from_group()` methods to subscribe/unsubscribe coordinator …

RFC Zigpy group management framework.

---

tests/test_types.py
zigpy/types/basic.py

`struct.unpack('<f', data)` requires buffer size in bytes to match the format string exactly. `zigpy.types.Single.deserialize(b'1234')` would work, but `zigpy.types.Single.deserialize(b'12345')` not.
Deserializing a buffer containing more than just float data fails:
```
2019-05-21 00:00:24 ERROR (MainThread) [bellows.ezsp] Exception running handler
Traceback (most recent call last):
File "/home/ha/src/bellows/bellows/ezsp.py", line 243, in handle_callback
handler(*args)
File "/home/ha/src/bellows/bellows/zigbee/application.py", line 211, in ezsp_callback_handler
self._handle_frame(*args)
File "/home/ha/src/bellows/bellows/zigbee/application.py", line 244, in _handle_frame
tsn, command_id, is_reply, args = self.deserialize(device, aps_frame.sourceEndpoint, aps_frame.clusterId, message) …
```

Fix float type (Single/Double) deserialization.

---

tests/test_types.py
tests/test_zcl_foundation.py
zigpy/types/struct.py
zigpy/zcl/foundation.py

PR #155 exposed a few areas, where Zigpy was incorrectly deserializing input data, particularly  handling of ConfigureReportingResponseRecord and WriteAttributeResponseRecord deserialization. Per ZCL specs, in case of success, only Status.Success field is sent back, with "attribute id"/"direction" fields ommited in order to save the bandwidth.
ZCL Specs sections `2.5.5.1.2` and `2.5.8.1.3`

Fix ConfigureReportingResponseRecord and WriteAttributeResponseRecord serialization/deserialization.

---

zigpy/endpoint.py
zigpy/zcl/clusters/lightlink.py

Use `ep_attribute` for Groups cluster access vs `cluster_id`, as some devices (XBee) use a non standard `cluster_id` for groups cluster.

Use `ep_attribute` when adding an endpoint to a group.

---

tests/test_appdb.py
tests/test_endpoint.py
tests/test_quirks.py
zigpy/appdb.py
zigpy/device.py
zigpy/endpoint.py
zigpy/quirks/__init__.py
zigpy/quirks/ikea/__init__.py
zigpy/quirks/keen/__init__.py
zigpy/quirks/kof/__init__.py
zigpy/quirks/smartthings/__init__.py
zigpy/quirks/xiaomi/__init__.py

Move Model and Manufacturer attributes to the Zigpy Device class.
In Zigbee, `manufacturer` and `model` values are tied to the `Basic` cluster and therefore to the endpoint. However logically, `Manufacturer` and `Model` notions apply to the entire physical Zigbee device, so it makes sense to implement those as Device class properties and this would clean up some of the Home Assistant ZHA component code.
For compatibility reasons, Endpoint instances still retain model/manufacture attributes, proxying those from the device instance. For now we still allow model/manufacturer overriding from quirks, however this is discouraged and will be removed in the future versions. Do we really need to override model/manufacturer at all?
As a side effect, this allow optimization during device discovery, …

Model & Manufacturer properties for zigpy.device.Device class.

---

zigpy/device.py

Don't request node_descriptor during device discovery, if the node
descriptor request was already triggered by incoming traffic.

Refactor node_descriptor request.

---

tests/test_quirks.py
tests/test_quirks_registry.py
zigpy/quirks/__init__.py
zigpy/quirks/ikea/__init__.py
zigpy/quirks/keen/__init__.py
zigpy/quirks/kof/__init__.py
zigpy/quirks/registry.py
zigpy/quirks/xiaomi/__init__.py

With the quirks number growing, keeping all the quirks in a flat list and iterating over the entire list for matching is not optimal anymore. 
Since 90% of the quirks could be tied to a specific model and manufacturer, this PR refactors quirks device registry into multidimensional dict, indexed by `manufacturer` and `model`. This drastically reduces noise in the debug logs (5488 lines vs 1556 lines) and load time, most noticeable on the slower hardware like Raspberry PIs
This could be improved even more, by defining at least the `manufacturer` in the signature for quirks that still miss it.

Quirks Device match refactoring.

---

tests/test_quirks_registry.py
zigpy/quirks/registry.py

Based on https://github.com/zigpy/zigpy/pull/183, adds a list of `(manufacturer, model)` tuples to signature, allowing one-to-many quirk-to-device matching based on manufacturer and model.

Allow multiple manufacturer/model in quirks signature

---

zigpy/quirks/__init__.py

Don't override endpoint's manufacturer and/or mode from quirks.

Don't override endpoint's manufacturer/model from quirks.

---

tests/test_zcl_foundation.py
tests/test_zdo_types.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

ZCL and ZDO statuses may contain status values from the lower levels (NWK, MAC). Don't fail deserialization for those.

Don't fail deserialization of undefined statuses

---

README.md

Update README.md in dev branch with mention PyPI release packages with links to the projects actively used by Zigpy on PyPI today.
I thought it worth mentioning since https://pypi.org/project/zigpy-homeassistant/ is used instead of https://pypi.org/project/zigpy/
Same with https://pypi.org/project/bellows-homeassistant/ being used instead of https://pypi.org/project/bellows/
and https://pypi.org/project/zigpy-xbee-homeassistant/ is used instead of https://pypi.org/project/zigpy-xbee/

Update README.md with links to PyPI release packages (dev branch)

---

tests/test_endpoint.py
zigpy/endpoint.py
zigpy/quirks/__init__.py
zigpy/zcl/__init__.py

When instantiating clusters, mark clusters as server/client accordingly.

Differentiate input/output cluster instances.

---

tests/test_zcl_foundation.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py

Implement ZCL General (global) Commands as an Enum.
Update ZCL General (global) commands schema.

Refactor ZCL foundation COMMANDS.

---

tests/test_endpoint.py
tests/test_zcl.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py
zigpy/zcl/foundation.py

write_attributes() used to have two different functions:
- issue "write attributes" request
- issue "read attributes response" reply
read_attribute_response was used for `general.Time` cluster, but since it has nothing to do with writing 
attributes, split it into a separate method.
Refactor `_discover()` method into a general (global ZCL cluster) command method.

Refactor Cluster.write_attributes()

---

tests/test_application.py
tests/test_device.py
tests/test_endpoint.py
tests/test_zcl.py
tests/test_zdo.py
tests/test_zigbee_util.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zdo/__init__.py

ATM all radios share more or less similar code, where radio has to track request/reply session and handle inbound traffic differently, if it is a part of a reply. This PR moves all this logic into Zigpy, so now radios are just responsible for sending data out and wait for transmission ACK/NAK. All incoming traffic is passed to zigpy as is and zigpy takes care of the reply traffic.

WIP handle request/reply interactions in zigpy

---

zigpy/application.py
zigpy/device.py

Remove timeout parameter from ControllerApplication.request() method.
Use keyword only parameters.

Remove timeout parameter.

---

zigpy/zdo/__init__.py

When binding, the destination endpoint (the endpoint on the coordinator stick) should be 1.
This could be improved in the future to receive the dst endpoint as a parameter.

fix binding dst endpoint

---

tests/test_application.py
tests/test_zdo.py
zigpy/application.py
zigpy/zcl/__init__.py
zigpy/zdo/__init__.py

Implement `ControllerApplication.get_dst_address()` helper. This can be overridden in radios so radio lib could provide a correct destination address for `zdo.bind()` & `zdo.unbind()` specifically for radios (ConBee) which receive data only on specific endpoints.

Refactor cluster binding.

---

tests/test_application.py
tests/test_device.py
tests/test_endpoint.py
tests/test_zcl.py
tests/test_zcl_clusters.py
tests/test_zdo.py
tests/test_zigbee_util.py
zigpy/__init__.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py
zigpy/zdo/__init__.py

Keep request/reply tracking in Zigpy. Make radio libraries only responsible for sending and receiving data without any further processing.

Refactor ControllerApplication.request()

---

README.md

Update README.md to mention experimental ZiGate support plus links to code/library and hardware.
@doudz has now publish zigpy-zigate v0.x.0 which has experimental support for ZiGate to Zigpy
https://github.com/doudz/zigpy-zigate
zigpy-zigate 0.1.0 to 0.4.0 versions released so far on PyPI
https://pypi.org/project/zigpy-zigate/#history
Requires ZiGate firmware 3.1a or later firmware version which has added a raw mode
https://zigate.fr/tag/firmware/

[DEV] Update README.md to mention experimental ZiGate support

---

tests/test_endpoint.py
zigpy/endpoint.py
zigpy/zcl/__init__.py

Use ZLL profile id only for `LightLink` cluster specific commands.

Override ZLL profile id for replies.

---

zigpy/zcl/foundation.py

Don't `repr()` cluster specific commands as Global commands.

Don't use Command enum for cluster specific commands.

---

tests/test_types.py
zigpy/appdb.py
zigpy/types/named.py

Since we represent `EUI64` address as a list of 8 bytes, keep LSB portion in the lower indexes of the list and MSB in the higher indexes. This also makes `EUI64` class just a fixed list of 8 `uint8_t` elements.

Refactor EUI64 class.

---

README.md

Update README.md listing ETRX357 series as compatible hardware with Zigpy (via bellows)
- Telegesis ETRX357USB (Note! First have to be flashed with other EmberZNet firmware)
- Telegesis ETRX357USB-LRS (Note! First have to be flashed with other EmberZNet firmware)
- Telegesis ETRX357USB-LRS+8M (Note! First have to be flashed with other EmberZNet firmware)
PS: Not sure if the newer ETRX358x series of Telegesis modules are also compatible with bellows?

Update README.md listing ETRX357 series as compatible hardware

---

setup.py
tests/test_application.py
tests/test_group.py
zigpy/application.py
zigpy/group.py
zigpy/zcl/__init__.py

Implement sending ZCL requests to multicast groups. ATM only ZCL clusters are supported.
```
group_id = 0x0100
group = application_controller.groups[group_id]
status, msg = await group.on_off.toggle()
status, msg = await group[6].toggle()
```

Group request method.

---

zigpy/zdo/__init__.py

Use debug level for unknown/unsupported ZDO requests.

Debug log level for zdo.

---

tests/test_ota_provider.py
zigpy/ota/provider.py

The chances of finding the four byte OTA header erroneously are slim but you can avoid searching by just reading the offset straight from the container file.

Extract IKEA OTA image offset and size directly from the container

---

README.md

Add a "Developer references" section to README.md and to added this link to Silicon Labs video playlist of ZigBee Concepts: Architecture basics, MAC/PHY, node types, and application profiles
- https://www.youtube.com/playlist?list=PL-awFRrdECXvAs1mN2t2xaI0_bQRh2AqD

Add a "Developer references" section to README.md

---

zigpy/ota/provider.py

Disable content type check for IKEA firmware image download.
IKEA OTA image server seems to be providing different content-types: `content-type: json` or `content-type: application/octet-stream` depending on the region. 
Fixes #264

Don't enforce content-type for IKEA firmware requests.

---

tests/test_endpoint.py
zigpy/device.py
zigpy/endpoint.py

This PR accounts for endpoints that have the status of inactive. This allows devices such as: lumi.remote.b286opcn01, lumi.remote.b486opcn01, lumi.remote.b686opcn01 to join the network as they report 6 endpoints each but 4 of them report inactive status.

Allow inactive endpoints

---

tests/test_ota_provider.py
zigpy/ota/__init__.py
zigpy/ota/provider.py

Adds provider to support Ledvance zigbee firmware updates. Provides updates for Sylvania, Osram, etc. Tested against Osram Lightify Gardenspot RGB.

add ledvance fw provider

---

README.md

Update README.md with link to experimental "zigpy-cc" by @sanyatuning with TI CC chip for Zigpy when using custom Z-Stack firmware from the Zigbee2mqtt project by @Koenkk
https://github.com/sanyatuning/zigpy-cc
Listing all TI CC chips supported by the custom Z-Stack-firmware from the Zigbee2mqtt community
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator
CC2538 + CC2592 dev boards and USB sticks should also be supported by zigbee-herdsman that this "zigpy-cc" module is based on according to Zigbee2mqtt and ioBroker communities
Koenkk/zigbee2mqtt#2372
https://github.com/ioBroker/ioBroker.zigbee

Update README.md with link to the zigpy-cc module for experimental TI CC chip support with custom Z-Stack firmware

---

tests/test_device.py
tests/test_quirks.py
zigpy/device.py
zigpy/quirks/__init__.py

This PR adds a flag to the device object to signify that a device should or should not skip configuration. It defaults to False. This will be used to handle Xiaomi devices cleanly (skipping binding and skipping report configuration) now that the newer devices are Zigbee certified and need to be configured.

Add flag to device to allow skipping configuration

---

tests/test_appdb.py
zigpy/appdb.py
zigpy/zcl/__init__.py

- Prevent saving of attribute updates and node descriptors to persistent storage if device is not fully initialized
- Don't save uninitialized device into persistent storage
- Don't use cluster_id as a foreign key for attributes
Fixes #289

Deffer attributes updates for uninitialized devices.

---

zigpy/zcl/clusters/general.py

This change allows to run zha.issue_zigbee_cluster_command from HA without "wrong number of arguments" error
ZigBee Cluster Library Specification:

Fix Identify cluster trigger_effect command arguments

---

zigpy/ota/provider.py

Explicitly send a content type header on firmware get requests to allow aiohttp json decoder to work more reliably.

Send content-type header on firmware get requests

---

zigpy/ota/provider.py

The `Content-Type` header introduced in #299 will be ignored by any compliant HTTP server when sent with a GET request. `Accept` is the appropriate header to use here, since we're expecting only JSON responses.
I've also documented the purpose of the `response.json(content_type=None)` line and removed that relaxation for the Ledvance provider, since their responses already have the appropriate `Content-Type`.

Use Accept instead of Content-Type in firmware provider GET requests

---

tests/test_types.py
tests/test_zcl_foundation.py
tests/test_zdo_types.py
zigpy/appdb.py
zigpy/endpoint.py
zigpy/ota/image.py
zigpy/profiles/zha.py
zigpy/profiles/zll.py
zigpy/types/basic.py
zigpy/types/named.py
zigpy/zcl/clusters/security.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

Refactor enum base class to automatically create an "undefined" member in case the value is not defined for that enum.
Use EnumIntFlags for `bitmaps`

Refactor Zigbee enum and bitmap data types

---

tests/test_zdo_types.py
zigpy/types/named.py
zigpy/zdo/types.py

Fixes `2020-02-13 21:44:21 WARNING (MainThread) [zigpy.zdo] [0x5b26:zdo] Unknown ZDO cluster 0x8038`
Produces:
```
2020-03-16 18:29:30 DEBUG (MainThread) [zigpy.zdo] [0xd3c2:zdo] ZDO request 0x8038: [<Status.SUCCESS: 0>, <Channels.ALL_CHANNELS: 134215680>, 20, 1448, [161, 176, 157, 156, 184, 157, 185, 162, 157, 157, 158, 189, 189, 156, 156, 164]]
2020-03-16 18:29:30 DEBUG (MainThread) [zigpy.zdo] [0xd3c2:zdo] Unsupported ZDO request:0x8038
```
But currently not processed in any way. Maybe could use to pick a better channel after processing reports from a few devices..

Add support for Mgmt_Nwk_Update ZDO commands

---

tests/test_zcl.py
tests/test_zcl_foundation.py
tests/test_zdo_types.py
zigpy/types/basic.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py

Make DataType registry a class with a Python  Type to DataType ID lookup method.
Use new DataType for `TypeValue`  class.

Refactor ZCL DataTypes

---

tests/test_endpoint.py
tests/test_zcl.py
zigpy/zcl/__init__.py

When receiving an attribute report or ReadAttribute command response, restore enum value name.

Normalize attribute reports and  Attribute Reads

---

tests/test_zdo_types.py
zigpy/types/named.py

I'm backporting a few changes from https://github.com/puddly/zigpy-znp.
The rationale for this addition is to potentially replace the single numeric `channel` in `ControllerApplication.form_network` and the channel list in `ControllerApplication.update_network` with a `Channel` bitmask:
https://github.com/zigpy/zigpy/blob/8236bc1a037b4a296cf565de2341471cd5fcecd5/zigpy/application.py#L62
https://github.com/zigpy/zigpy/blob/8236bc1a037b4a296cf565de2341471cd5fcecd5/zigpy/application.py#L74-L82
Thoughts?

Add Channels.from_channel_list to create masks from numeric lists

---

zigpy/appdb.py

Quirks often update attributes on unexisting clusters and endpoints.

Relax attributes table schema.

---

tests/test_zcl.py
tests/test_zcl_foundation.py
zigpy/zcl/foundation.py

Deserialize/Serialize `write_attributes` and `configure_reporting` command responses per ZCL specs.
In case of all successfully configured/written attributes serialize/deserialize only Success status. Otherwise deserialize/serialize only failed attributes.

Refactor write attr and configure reporting responses.

---

tests/test_zcl.py
zigpy/zcl/__init__.py

Implement `write_attributes_undivided()` ZCL command.
The Write Attributes Undivided command is generated when a device wishes to change the values of one or more attributes located on another device, in such a way that if any attribute cannot be written (e.g., if an attribute is not implemented on the device, or a value to be written is outside its valid range), no attribute values are changed.
In all other respects, including generation of a Write Attributes Response command, the format and operation of the command is the same as that of the Write Attributes command

Add "write_attributes_undivided()" command

---

tests/test_types.py
zigpy/types/basic.py

Allow instantiation using string values, eg `t.enum8("42")` or `t.enum8("0x28")` to maintain backward compatibility from the times when `enum`s where just `int`s.

Refactor enums.

---

.coveragerc
tests/test_appdb.py
tests/test_application.py
tests/test_config.py
zigpy/application.py
zigpy/config.py
zigpy/typing.py

Pass configuration to Zigpy using a voluptuous schema. ATM Zigpy supports the following schema:
```yaml
device:
path: /dev/ttyUSB0
ota:
ikea_provider: true
ledvance_provider: true
otau_directory: /config/ota_updates
database_path: /path/to/zigbee.db
```
Radio modules are allowed to extend schema to include module specific options, eg adding `baudrate` and/or flow control options as well as radio specific configuration options.

Pass Zigpy configuration using voluptuous schema.

---

zigpy/config.py

Don't require DB and OTA path to be existing paths.

Relax schema checks.

---

tests/test_zdo_types.py
zigpy/zdo/types.py

`SizePrefixedSimpleDescriptor.deserialize` returns an instance of `SimpleDescriptor`, which breaks code that relies on `isinstance(Obj.deserialize(...), Obj)` being true.

Fix deserialization type bug with `SizePrefixedSimpleDescriptor`

---

tests/test_zigbee_util.py
zigpy/util.py

`LocalLogMixin` introduces a few more stack frames with its helper methods. This removes useful info from logs:
```
[2020-04-14 18:51:07] DEBUG [zigpy.zcl.log:486] [0x8758:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=True is_reply=True disable_default_response=True> manufacturer=4447 tsn=250 command_id=Command.Report_Attributes>
[2020-04-14 18:51:07] DEBUG [zigpy.zcl.log:486] [0x8758:1:0x0000] ZCL request 0x000a: [[<Attribute attrid=65281 value=<TypeValue type=LVBytes, value=b'\x01!\xd1\x0b\x03(\x15\x04!\xa8\x13\x05!P\x00\x06$\x01\x00\x00\x00\x00\n!\xae^d\x10\x00\x0b!\xc7\x01'>>]]
[2020-04-14 18:51:07] DEBUG [zigpy.zcl.log:486] [0x8758:1:0x0000] Attribute report received: …
```

Improve logging context by ignoring `LocalLogMixin`'s stack frames in Python 3.8+

---

zigpy/config.py

Don't require for the device path to exist.

Relax device schema

---

tests/test_appdb.py
tests/test_application.py
zigpy/application.py

`ControllerApplication.probe()` method receives `SCHEMA_DEVICE` as config and should return True if radio was successfuly detected or False otherwise.

Require radio libs to implement probe() method for ControllerApplication class

---

tests/test_config.py
zigpy/application.py
zigpy/config.py
zigpy/config/__init__.py
zigpy/config/defaults.py
zigpy/config/validators.py

Add `network` section and schema into default `SCHEMA_ZIGPY`
example
```
network:
update_id: 1
pan_id: 0x1234
extended_pan_id: 00:11:22:33:44:55:66:77:88
network_key: [1, 2, 3, 4, ... 16]
channels: [15, 20, 25]
channel: 15
```

Add schema for network parameters

---

zigpy/util.py

Use a logger instead of just printing messages.

Use logger for retries loggin

---

tests/test_config.py
zigpy/config/validators.py

`not any` -> `not all`. Also added check for ensuring each element is of the right type, to avoid raising a `TypeError` when doing `0 <= e <= 255` with a non-integer `e`.

Fix logic bug with cv_key validator

---

tests/test_zcl.py
zigpy/zcl/__init__.py

Send default response for received Report_Attributes command, unless `disable_default_response` is set.
Fixes #406

Send default response for received Report_Attributes command

---

tests/test_endpoint.py
zigpy/endpoint.py

When removing a group which is not there, Status.NOT_FOUND is not a hard failure. Same for Status.DUPLICATE_EXISTS when adding an endpoint to a group.
Fixes #397

Don't treat all unsuccessful statuses as hard failures.

---

tests/test_zigbee_util.py
zigpy/util.py

Instead of assertion error raise ControllerApplication exception and retry request if applicable.

On duplicate TSNs raise ControllerApplication exception

---

README.md

Update README.md with RaspBee II (a.k.a. RaspBee 2)
[RaspBee II (a.k.a. RaspBee 2)](https://www.dresden-elektronik.com/product/raspbee-II.html) GPIO radio adapter from [dresden elektronik](https://www.dresden-elektronik.de)
Also changed "Dresden-Elektronik" to "dresden elektronik" because that is how they market/brand their company name.

Update README.md with RaspBee II (a.k.a. RaspBee 2)

---

tests/test_types.py
zigpy/types/struct.py

`Struct.__init__` uses `isinstance(other, self.__class__)` for its "copy constructor", which silently fails if a type is declared optional by using `t.Optional(SomeStruct)`. This fix feels a little hacky because of the MRO list traversal and relying on the `Optional` class's name but I can't really see an alternative that doesn't involve redoing a bunch of type stuff elsewhere in the codebase.

Fix `isinstance` check for optional `Struct` subclasses

---

zigpy/zcl/__init__.py

Keep a registry of CustomCluster classes. Would allow zha-device-handlers to run some basic sanity checks on Custom Clusters.

Registry of CustomCluster classes

---

zigpy/zdo/types.py

`NodeDescriptor` is the only `Struct` subclass that has its own initializer. This breaks the typing fix from pull request #416 for this specific class, which appears to be the only unusual `Struct` subclass.
The one difference between `NodeDescriptor.__init__` and the old `Struct.__init__` is the inclusion of a `self._valid` flag. This flag isn't actually used so removing the initializer entirely should be fine.
---
I'm hoping to eventually bring in parts of the typed "structure" system from zigpy-znp back into zigpy, which should eliminate most of these hacks. You can see how optional parameters look [when created](https://github.com/zha-ng/zigpy-znp/blob/c4d955453342b0ad481ab10cde3becaee6db0c7a/zigpy_znp/commands/sys.py#L62-L89) and how they behave in their [unit …

Remove unused `NodeDescriptor.__init__` that breaks `t.Optional` type fix

---

zigpy/zcl/__init__.py

Process manufacturer specific client/server commands, even if ZCL client/server commands do not exist.

Merge manufacturer commands even with empty ZCL commands

---

tests/test_zcl.py
zigpy/zcl/__init__.py

In addition to #421 allow access to cached ZCL attributes via `cluster.get(Union[int, str])` method.

Implement get() method to access cached ZCL attributes.

---

zigpy/appdb.py

When restoring devices, log device nwk, endpoint id and cluster id during attribute cache restoration.

Extra debug log on restoring app state

---

tests/test_zcl.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/zcl/__init__.py

0.22.2 Release
- Implement get() method to access cached ZCL attributes (#441)
- Extra debug log on restoring app state (#442)

0.22.2 Release

---

tests/test_types.py
zigpy/types/basic.py
zigpy/zcl/foundation.py

`struct.pack` and `struct.unpack` are used internally for serialization and deserialization, which ensures `NaN` and the two infinities are handled properly. All that the conversion really does is shrink/expand the size of the exponent and fraction.
Note: this implementation is limited to the precision of the Python runtime (as was the old) so `t.Double` will not be as precise on 32-bit platforms with a Python implementation that doesn't use double-precision floats. This has the side effect of `t.Double(t.Double.deserialize(foo)[0]).serialize() == foo` not necessarily being true (though the two values will be close enough).

Implement Half-precision floating point numbers

---

tests/test_struct.py
tests/test_types.py
tests/test_zcl_foundation.py
zigpy/types/basic.py
zigpy/types/named.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

The major improvement here is integer `Enum`s' and their members' types now make sense. This simplifies a bit of code.
Before:
```Python
import zigpy.types as t
class TestEnum(t.enum8):
Member = 0x00
assert isinstance(TestEnum.Member, t.uint8_t) is False  # this is annoying
assert type(TestEnum.Member.value) is int  # this breaks a lot of stuff
TestEnum.Member.serialize()  # works only because TestEnum itself has a serialize method
```
After:
```Python
assert isinstance(TestEnum.Member, t.uint8_t) is True
assert type(TestEnum.Member.value) is t.uint8_t
TestEnum.Member.serialize()  # no special handling needed
```
Other improvements:
- `t.uint8_t(-1)` and `t.uint8_t(256)` throw a `ValueError`. The former's `OverflowError` is re-raised as a `ValueError`.
Problems:
- `t.LVList` not being an …

Make fixed-size integers and Enum subclasses' types behave properly

---

README.md

Update README.md to mention support for ITEAD Sonoff ZBBridge if flashed with Tasmota and EmberZNet 6.5.x.x
See https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html and https://templates.blakadder.com/sonoff_ZBBridge.html
This solves https://github.com/zigpy/zigpy/issues/385
@Adminiuga Please also see matching PRs https://github.com/zigpy/bellows/pull/285 & https://github.com/home-assistant/home-assistant.io/pull/14124

Update README.md to mention ITEAD Sonoff ZBBridge with Tasmota

---

tests/test_struct.py
zigpy/ota/image.py
zigpy/types/struct.py
zigpy/zdo/types.py

Use `t.StructField(requires=...)` to replace a couple of custom serialization/deserialization functions. Affected classes are `zigpy.ota.image.OTAImageHeader` and `zigpy.zdo.types.NwkUpdate`.

Simplify some structs by using `t.StructField(requires=...)` instead of custom `serialize`/`deserialize` methods

---

README.md

Updates README.md  with additional supported CC1352x and CC2652x Zigbee chips from Texas Instruments.
No code changes. CC1352P, CC1352R, CC2652P, CC2652R, CC2652RB use the same TI Zigbee coordinator firmware/API version and are all already supported by the current branch with existing ZHA and zigpy/zigpy-cc libraries.
Also merged "CC2530 + CC2591" and "CC2530 + CC2592" lines to one line with "CC2530 + CC2591/CC2592".

Update README.md to list all TI CC1352x and CC2652x chips

---

tests/test_types.py
tests/test_zcl.py
tests/test_zcl_foundation.py
tests/test_zdo_types.py
tox.ini
zigpy/types/basic.py
zigpy/types/named.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/clusters/lightlink.py
zigpy/zcl/clusters/protocol.py
zigpy/zcl/clusters/security.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

The main change is overloading subclass and instance checks in the list metaclass so that the classes can be used as types:
```Python
class LVListSubclass(t.LVList, length_type=t.uint8_t, item_type=t.uint16_t):
pass
assert issubclass(LVListSubclass, t.LVList[t.uint8_t, t.uint16_t])
assert isinstance(LVListSubclass(), LVListSubclass)
assert isinstance(LVListSubclass(), t.LVList[t.uint8_t, t.uint16_t])
```
This still allows for the creation of anonymous `t.LVList`s that work as you'd expect. With #444, most of the weirdness in the type system will be fixed and hacks relying on the names of classes can be removed (e.g. https://github.com/zigpy/zigpy/blob/41986610e84a51cd89ff09701ce1a055d7c9a6a6/zigpy/zcl/foundation.py#L136-L152).

Concrete List/LVList/FixedList types

---

setup.py
tox.ini

Allows you to do `pip install zigpy[testing]` and then just run `pytest`. 
Also, `setup.py test` is deprecated (https://github.com/pypa/setuptools/issues/1684) and `tests_require` aren't used by `tox`.

Update setup.py and tox.ini to fully setup the testing env with pip

---

tests/test_zcl_foundation.py
tests/test_zdo_types.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

The only one left is `AttributeReportingConfig`, which has a field whose data type is determined by a previous field. This isn't supported by the `struct` module right now without a few changes.
One ambiguous class that I saw is `ConfigureReportingResponseRecord`. The spec (**2.5.10.1**) says that:
> Note that attribute status records **are not included** for successfully configured attributes, in order to save bandwidth. In the case of successful configuration of all attributes, only a single attribute status record SHALL be included in the command, with the status field set to SUCCESS and the direction and attribute identifier fields omitted.
It doesn't say "SHALL not", only "are not". Does this mean that status records for successfully configured attributes can possibly be present? If …

Simplify attribute record types in foundation

---

README.md

Older version of 6.5.x.x of EmberZNet is no longer needed as bellows now support EZSP v4/v5/v6/v7/v8

Update README.md remote need for older EmberZNet as EZSP v4/v5/v6/v7/v8 is now supported

---

README.md

Update README.md to first of all recommend zigpy-znp for Z-Stack 3.x.x firmware and zigpy-cc for Z-Stack Home 1.2.x firmware.
Also re-sorted hardware manufacturers to all be listed in alphabetical order and adapters re-sorted to list newer adapters first.

 Update README.md to separate Z-Stack 3.x.x versus Z-Stack Home 1.2.x

---

tests/test_struct.py
zigpy/types/struct.py

An unassigned annotated attribute is a field.
An assigned attribute of `StructField` class is a field.
An assigned and annotated attribute of `StructField` class is a field.
Anything else is not a field.

Refactor t.Struct fields

---

.gitignore
tests/test_struct.py
tests/test_zdo_types.py
zigpy/types/struct.py
zigpy/zdo/types.py

This is now not supported (and was never actually used in the codebase):
```Python
class TestStruct(t.Struct):
foo: t.Optional[t.uint8_t]
```
The following is also now invalid due to Python providing no way to get the order of annotated and unannotated attributes:
```Python
class TestStruct(t.Struct):
foo: t.uint8_t
bar = t.StructField(type=t.uint8_t)
baz: t.uint8_t
```
Instead, you have to use `None` as a type annotation (maybe it'd be better to use `t.StructField`??):
```Python
class TestStruct(t.Struct):
foo: t.uint8_t
bar: None = t.StructField(type=t.uint8_t)
baz: t.uint8_t
```

Remove unused `Optional` annotations from `Struct` and cache `fields`

---

.travis.yml
tests/__init__.py
tests/async_mock.py
tests/test_appdb.py
tests/test_application.py
tests/test_device.py
tests/test_endpoint.py
tests/test_group.py
tests/test_neighbor.py
tests/test_ota.py
tests/test_ota_provider.py
tests/test_quirks.py
tests/test_topology.py
tests/test_zcl.py
tests/test_zcl_clusters.py
tests/test_zdo.py
tests/test_zigbee_util.py
tox.ini

Migrate from asynctest to stdlib AsyncMock for py38.
Fixes https://github.com/zigpy/zigpy/issues/475

Migrate from asynctest to stdlib AsyncMock for py38

---

CONTRIBUTING.md

Update CONTRIBUTING.md link to isort has moved from https://github.com/timothycrosley/isort to https://github.com/PyCQA/isort
For rference see https://github.com/zigpy/zigpy/issues/467 & https://github.com/zigpy/zigpy/pull/488 & https://github.com/zigpy/bellows/pull/349

Update CONTRIBUTING.md URL link to isort has changed

---

zigpy/ota/provider.py

Change protocol for IKEA OTA firmware list URL.

Change IKEA OTA url to use http

---

tests/test_ota.py
tests/test_ota_validators.py
zigpy/ota/__init__.py
zigpy/ota/validators.py

Another fix for #497. This prevents zigpy from even considering the corrupted IKEA OTA files. Only known OTA containers from Silicon Labs with an invalid structure are rejected so this will not affect other firmwares.
I'm hesitant to include a ton of OTA files into the zigpy `tests/` directory so I've run it locally on every single IKEA OTA file downloaded from the current stable and test feeds, along with every OTA file from an older stable feed, and then every file in https://github.com/Koenkk/zigbee-OTA. All OTA images are marked either as "UNKNOWN" or "VALID", with eight images from the currently buggy IKEA feed being marked as "INVALID" (confirmed by testing with Silicon Labs' own firmware tool).
If you have other images you can test every file in a folder recursively:
```Python …
```

Reject invalid SiLabs upgrade images

---

zigpy/ota/__init__.py

Files placed in the OTA directory should be preferred over downloaded images when they have the same version.

File OTA provider should be preferred

---

zigpy/types/basic.py

Fixes https://github.com/home-assistant/core/issues/40767
Associated Python bug report: https://bugs.python.org/issue41889

Make `t.uint_t`-based `IntFlag` enums compatible with 3.8.6

---

zigpy/config/__init__.py
zigpy/ota/provider.py

Allow configuration of IKEA update URL via `ikea_update_url` configuration parameter.
For example in Home Assistant core `configuration.yaml` add:
```yaml
zha:
zigpy_config:
ota:
ikea_provider: true
ikea_update_url: http://fw.test.ota.homesmart.ikea.net/feed/version_info.json
```

Allow configuration of IKEA update URL

---

tests/test_ota.py
tests/test_ota_validators.py
zigpy/ota/__init__.py
zigpy/ota/validators.py
zigpy/types/basic.py

<sup>(#504 was auto closed when I force-pushed to my `dev` branch)</sup>
https://github.com/zigpy/zigpy/pull/500 logs `OTAImage` validation statuses with the `DEBUG` log level and invalid images with the `ERROR` log level. The inclusion of `OTAImage` objects in these log message will cause them to be logged in their entirety, which will include over 200kb of image data into logs during normal use when invalid images are encountered.
This change adds verbose validation error messages and replaces the `image` object with `image.header` within the log messages.
Future revisions to the OTA system could include a way to track an image's origin so `image.header` could be replaced with that instead.

Use verbose OTA image validation errors

---

zigpy/device.py
zigpy/endpoint.py

log failed discoveries as `warnings`.  Include some additional information like if endpoint discover failed or endpoint id etc.

Refactor logging during device discovery

---

tests/test_appdb.py
zigpy/appdb.py

INSERT OR REPLACE deletes and inserts when the record already exists.
Since table constraints have ON DELETE CASCADE, the attributes (and probably endpoints and so on) were being deleted when an existing device is saved. 
After rebooting HA, no quirk would match since the device would have not manufacturer attr.
Should we also change the other INSERT OR REPLACE commands?

Fix attributes being lost when an existing device is re-added

---

tests/test_appdb.py
tests/test_device.py
zigpy/appdb.py
zigpy/device.py

This is no longer needed, as it was done to ease the transition for existing setups which did not have node descriptors.

Don't query node descriptor on incoming messages

---

setup.py
tests/test_appdb.py
zigpy/appdb.py
zigpy/application.py

Refactor `appdb.PersistingListener` to use [`aiosqlite`](https://github.com/omnilib/aiosqlite) so there's no disk io in the loop.
Fixes https://github.com/home-assistant/core/issues/42345
Adds new method `ControllerApplication.pre_shutdown()` which should be called instead of the `shutdown()` method implemented by the radio libraries.

Refactor persisting listener to use aiosqlite

---

tests/test_appdb.py
zigpy/appdb.py

Remove devices without any endpoints. This compliments fix in https://github.com/zigpy/zigpy/pull/515 since users still are going to experience the issue, unless they fully remove and re-pair the affected devices. This removes those affected devices on start up so user just have to re-pair the device.

Cleanup device on restart

---

setup.py

Bump up aiosqlite dependency. Prevents `aiosqlite` from logging as exception on device rejoin.

Bump up aiosqlite dependency

---

tests/test_zcl.py
zigpy/zcl/__init__.py

Return the default value, instead of throwing a KeyError when doing something like `cluster.get("no_such_attribute")`

Handle cluster.get("no_such_attr") correctly

---

README.md

List Texas Instruments with Z-Stack 3.x.x firmware and zigpy-znp as "Known working Zigbee radio modules" instead of as experimental.
Also added dresden elektronik and digi as prefix to deCONZ and XBee respetivly as all other radios also list the hardware manufacturer.

zigpy-znp with TI Z-Stack 3 is no longer experimental with zigpy-znp

---

tests/test_appdb.py
tests/test_application.py
tests/test_quirks.py
zigpy/application.py
zigpy/device.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py

1. Allow registration of `handle_message` handlers for incoming messages from uninitialized devices
2. Add `handle_message` event to remove ZHA hack
This would allow implementation of fast xiaomi initialization in quirks

Framework implementing message handlers from uninitialized devices

---

README.md

zigpy-zigate with ZiGate 3.1d firmware should no longer be considered as experimental according to @doudz
Reference:
https://github.com/home-assistant/home-assistant.io/pull/15685
https://github.com/home-assistant/core/pull/43252
https://zigate.fr/2020/10/12/maj-firmware-zigate-version-3-1d/

Update README.md moving zigate from experimental to known working

---

tests/test_quirks.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py

Fixes https://github.com/zigpy/zigpy/issues/566
Using the same instance of the "model" default dict, causes different manufacturers to share the list for the same "model" name.

Fixe regression introduced in #555

---

tests/test_appdb.py
tests/test_application.py
tests/test_zdo.py
zigpy/application.py
zigpy/zdo/__init__.py

1. Schedule a ZDO Mgmt_Leave_req to the device being removed
2. If the device being removed is an "End Device", then schedule sending a ZDO Mgmt_Leave_req to each device which has "device being removed" in their neighbor tables
Don't wait for the actual request completion. Remove device from `ControllerApplication.devices` dict on successful reply to ZDO request or on a 30s timeout.
This PR effectively removes requirement to implement `ControllerApplication.force_remove()` method.

Refactor ControllerApplication.remove() method

---

tests/test_appdb.py
tests/test_quirks.py
tests/test_quirks_registry.py
tests/test_zcl_foundation.py
zigpy/appdb.py
zigpy/const.py
zigpy/device.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py

- Increase coverage
- Refactor `zigpy.device.Device.get_signature()` to use same constants as quirks. This is a breaking change.

Increase coverage

---

tests/test_types.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/types/named.py
zigpy/zdo/__init__.py

Add `dst_addressing_mode indicator` to the message handlers to provide more insight about how the message was received. 
Some received ZDO commands should behave differently, if the incoming message was a broadcast or a unicast. And keep different counters depending on the message type.

Add dst_addressing indicator to incoming message handlers

---

tests/test_ota.py
tests/test_ota_image.py
tests/test_ota_provider.py
tests/test_ota_validators.py
tests/test_zcl_clusters.py
zigpy/ota/__init__.py
zigpy/ota/image.py
zigpy/ota/provider.py
zigpy/ota/validators.py

This change centralizes all OTA image parsing into a `zigpy.ota.image.parse_ota_image` function that properly deals with IKEA containers and now Hue SBL images. A side effect of this change is allowing `FileProvider` to properly unwrap IKEA images (rather than scanning for the Zigbee OTA header in the first 512 bytes) and all future weird file types without any necessary changes.
`CachedImage` was rewritten to be a container around any type of image that has a header and can be serialized. I've also added a `CachedImage.cached_data`, which prevents the wrapped image from being repeatedly serialized every time a block is requested.

Single function for OTA image parsing, CachedImage simplification, and Hue SBL images

---

tests/test_quirks.py
tests/test_quirks_registry.py
zigpy/quirks/registry.py

This is the first step in setting up zhaquirks for custom quirks. Reversing the zigpy quirk matching order to prioritize more recently registered quirks is necessary because a custom quirk may attempt to import custom clusters from `zhaquirks` itself when replacing an existing quirk, which will cause the existing quirk to be registered first and always match.
May require some real-world testing but I don't think any quirks exist that rely on load order like this.
Thank you @dmulcahey for coming up with this much simpler solution and steering me away from rewriting `zigpy.quirks` to requiring quirks to be explicitly registered 😄

Prefer recently-registered quirks when there are multiple matches

---

tests/test_appdb.py
zigpy/appdb.py

Catch, log and swallow exceptions in the `PersistingListener` worker task. Fixes a regression introduced in #588: saving a device with an  invalid node descriptor causes the worker task to be terminated prematurely on an exception. 
the fix:
1. Catch exceptions in the worker, log them and ignore
2. Don't save devices without a valid node descriptor

Don't let PersistingListener worker task die

---

tests/test_zcl.py
zigpy/types/named.py

Make the `zigpy.types.named.Bool` an `enum8` type, to allow other than 0 & 1 value for the bool type, as some devices are overloading this type with other values, requiring more complex handling/work arounds

Make Bool type an enum8

---

tests/test_quirks.py
tests/test_quirks_registry.py
zigpy/quirks/registry.py

`CustomDevice` with a "model" only signature key now will match any manufacturer, assuming the rest of the signature matches.

Support wildcard manufacturer quirks

---

tests/test_zcl.py
tests/test_zcl_clusters.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py

Change method signature, send the actual ZCL header to provide more context to the handler.
This PR is a result to the [comment](https://github.com/zigpy/zigpy/pull/622#issuecomment-761615829) and is aimed to provide more context to the command handler, like whether a default response should be suppressed or not.

Refactor Cluster.handle_cluster_request() method

---

tests/test_endpoint.py
tests/test_zcl_clusters.py
zigpy/endpoint.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py

Add [dst_addressing](https://github.com/zigpy/zigpy/pull/591) parameter to `handle_cluster_request()` and `handle_cluster_request()` general methods. This PR is a continuation of the issue raised in [comment](https://github.com/zigpy/zigpy/pull/622#issuecomment-761615829) as the default response command should not be sent to incoming messages received via GroupAddress or incoming broadcasts. The "dst_addressing" parameter provides the required context to make the decision.

Add dst_addressing default parameter to handle_cluster_*_request() method

---

tests/test_struct.py
tests/test_zdo_types.py
zigpy/types/struct.py

Some types (namely node and neighbor descriptors) include bitfields, which zigpy does not yet natively support. This change includes all properties in the string representation of a struct.
For example, `zigpy.zdo.types.Neighbor` before:
`
Neighbor(extended_pan_id=a8:c0:3b:db:53:ca:60:a8, ieee=00:0b:57:ff:fe:8d:4f:83, nwk=0xDE0E, packed=37, permit_joining=<PermitJoins.Unknown: 2>, depth=15, lqi=97)
`
And after:
`
Neighbor(extended_pan_id=a8:c0:3b:db:53:ca:60:a8, ieee=00:0b:57:ff:fe:8d:4f:83, nwk=0xDE0E, packed=37, permit_joining=<PermitJoins.Unknown: 2>, depth=15, lqi=97, *device_type=<DeviceType.Router: 1>, *relationship=<Relationship.Sibling: 2>, *rx_on_when_idle=<RxOnWhenIdle.On: 1>)
`
Similarly, `OTAImage.header` before:
`
OTAImageHeader(upgrade_file_id=200208670, header_version=256, …

Include properties in Struct string representations

---

tests/test_zdo_types.py
zigpy/types/named.py

This functionality is duplicated by application code that needs to work with the specific channels represented by the bitmap. Complements the `from_channel_list` classmethod.
```Python
>>> import zigpy.types as t
>>> channels = t.Channels.from_channel_list([11, 12, 13, 25])
>>> list(channels)
[11, 12, 13, 25]
>>> t.Channels.from_channel_list(channels) == channels
True
>>> for channel in channels:  print(channel)
11
12
13
25
```

Make the `Channels` type iterable

---

zigpy/appdb.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/util.py

Ran into a bizarre failing unit test in zigpy-znp caused by `asyncio.CancelledError` being an `Exception` subclass in Python 3.7 but a `BaseException` subclass in Python 3.8 and beyond. This causes coroutines that normally handle exceptions (e.g. infinite loops) to never actually quit when cancelled.
For example, the following task will not stop running in Python 3.7, but will in Python 3.8 and 3.9:
```Python
import asyncio
async def task():
while True:
try:
print("Running...")
await asyncio.sleep(1)
except Exception as e:
print(f"Caught an exception: {e!r}")
await asyncio.sleep(2)
async def main():
t = asyncio.create_task(task())
await asyncio.sleep(4)
print("Stopping task")
t.cancel()
await asyncio.sleep(10)
if __name__ == "__main__":
asyncio.run(main())
```

Do not catch `CancelledError` with `except Exception` in Python 3.7

---

tests/test_struct.py
zigpy/ota/image.py
zigpy/types/named.py
zigpy/types/struct.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/lightlink.py
zigpy/zcl/clusters/protocol.py
zigpy/zcl/clusters/security.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

Postponed annotation evaluation is mandatory in Python 3.10 and is already supported by Python 3.7 and above through `from __future__ import annotations`. Everything works except for this construct:
```Python
class Bar:
class Foo:  pass
foo: Foo
import typing
typing.get_type_hints(Bar)
```
It now unfortunately has to be done like this due to scope issues (unless very hacky stack frame traversal is added to `Struct.__init_subclass__`):
```Python
class Foo:  pass
class Bar:
Foo = Foo
foo: Foo  # This refers to the global `Foo`, the one in the class scope is not available
del Foo
```
All but two unit tests pass with the Python 3.10 alpha build (due to major changes to the `enum` module...) so it appears that nothing else is expected to break.

Switch to postponed annotation evaluation

---

README.md

Update zigpy README to remove lists of all specific hardware sticks/dongles/adapters as suggested by @Adminiuga in https://github.com/zigpy/zigpy/pull/696
> _All specific radios should be removed from Zigpy readme and only links to respective "protocol" implementations should be kept here. Radio specific supported models should be listed by each respective project._
Also see PRs which add/update removed information about compatible sticks/dongles/adapters to all radio libraries README files:
https://github.com/zigpy/zigpy-znp/pull/69
https://github.com/zigpy/zigpy-xbee/pull/118
https://github.com/zigpy/bellows/pull/411
https://github.com/zigpy/zigpy-deconz/pull/158
PS: Both https://github.com/zigpy/zigpy/pull/705 and https://github.com/zigpy/zigpy-znp/pull/69 are together also related to …

Update README.md to remove lists of specific hardware adapters

---

zigpy/zdo/types.py

These commands are usefull to get remote device binding table entries.

Add Mgmt_Bind_req and Mgmt_Bind_rsp ZDO commands.

---

zigpy/appdb.py

The `Discarding %s event` warning is logged with the `%s` left as is, instead of replacing the expected context of which event is being discarded.

Add context to the "Discarded Event" warning

---

tests/test_appdb.py
zigpy/appdb.py

Zigpy currently fails to start up if the database contains stray rows, which somehow happens with various user databases. Since #711 is going to take a bit more time to merge, it seems simpler to just temporarily fix this problem in time for the next release.

Handle stray database rows without crashing

---

tests/test_appdb.py
tests/test_application.py
tests/test_device.py
tests/test_endpoint.py
zigpy/appdb.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/exceptions.py

This is a continuation of the discussion started with https://github.com/zigpy/zigpy/pull/711#issuecomment-843597383 and my attempt at implementing some of the changes.
It's currently a WIP and no unit tests have been updated. That being said, IKEA remotes and bulbs feel like they join much more quickly.
Changes:
- No errors are caught during device initialization, the whole process has to work.
- Device initialization is cancelled and re-started every time a device joins or announces itself.
- Initialization more or less starts where it left off after every restart and can safely be called on already-initialized devices, in case they have no node descriptor or are missing some sort of information. This is done at startup and after any message is received from a partially-initialized …

Improved device initialization

---

tests/test_endpoint.py
zigpy/endpoint.py
zigpy/zcl/__init__.py

Zigpy allows for `Cluster` itself to be initialized (not a subclass!), whose instances don't have a `ep_attribute` attribute, causing this error (only when debug logging is enabled?).

Fix direct `Cluster` instances causing errors in `Endpoint.__repr__`

---

tests/test_ota_validators.py
zigpy/ota/validators.py

GBL images are not supposed to have trailing padding. I was only aware of Hue images that had `\x00` padding but apparently other images exist with `\xFF` padding. If an image is structurally sound and its CRC is valid, it should be accepted.

Ignore all GBL image padding

---

tests/test_appdb_migration.py
zigpy/appdb.py

Drop existing v4 tables and re-migrate from v3 schema if user downgraded zigpy and then upgraded again.
Fixes https://github.com/home-assistant/core/issues/52394

Re-migrate V4 database which was forcibly downgraded to v3

---

tests/test_appdb.py
tests/test_application.py
tests/test_device.py
zigpy/appdb.py
zigpy/device.py

Fixes the broken ZHA visualization in https://github.com/home-assistant/core/issues/53132
The improved device initialization PR (#744) switched away from empty `NodeDescriptor` objects in favor of `None` but `Device.__init__` did not actually set `device.node_desc = None`. The Home Assistant PR to update ZHA to support this behavior (https://github.com/home-assistant/core/pull/52610) unfortunately relied on `node_desc` being `None` and this inconsistently is causing problems.

Make `Device.node_desc` start off as `None` instead of being empty

---

zigpy/zcl/clusters/general.py

Not sure if we need a new type for "integers with special values", like `StartUpCurrentLevel`:
- `0x00` is the minimum
- `0xFF` is the previous value
- every other value is handled normally

Add ZCL7 start up attributes to `OnOff` and `LevelControl` clusters

---

zigpy/application.py

Allow probe method to return `zigpy.config.SCHEMA_DEVICE` dict, which contains auto detected radio settings.
For example, this could allow radio to autodetect port baudrate.

Update typing for the probe method

---

tests/databases/simple_v5.sql
tests/test_appdb.py
tests/test_appdb_migration.py
zigpy/appdb.py
zigpy/appdb_schemas/schema_v6.sql

Fixes #777
Also migrates the rows ignored by the v5 migration, since they still exist in the unversioned `attributes` table.

Relax `attribute_cache` schema and add a v4 to v6 re-migration

---

tests/test_application.py
tests/test_topology.py
zigpy/application.py
zigpy/device.py
zigpy/topology.py

I've looked over every reference to `Device.node_desc` in both zigpy and ZHA to hopefully make sure this is the last node descriptor bugfix PR.
Related PR: https://github.com/zigpy/zigpy-xbee/pull/119
HA issue: https://github.com/home-assistant/core/issues/53838#issuecomment-894806418

Fix `None` node descriptor issues with device removal and the topology scanner

---

zigpy/zcl/clusters/lighting.py

Basically https://github.com/zigpy/zigpy/pull/774 just with ``start_up_color_temperature``
The goal is to remove all lighting related Philips Hue related quirks. (See https://github.com/zigpy/zha-device-handlers/pull/993)
The ``start_up_color_temperature`` (0x4010) attribute is spec in ZCL v7 and https://github.com/zigpy/zigpy/pull/716 would implement this. However, that (way bigger) PR still looks like it's WIP.
In the meantime, https://github.com/zigpy/zigpy/pull/774 was merged to implement ``start_up_on_off `` and ``start_up_current_level``.
This already make these custom Philips clusters redundant: https://github.com/zigpy/zha-device-handlers/blob/8c61c6da4e44906183a4d96e022e67f8c2ba005d/zhaquirks/philips/__init__.py#L93-L104)
The custom Philips color cluster is still needed until …

Added start_up_color_temperature/0x4010 (from ZCL v7)

---

tests/test_appdb.py
tests/test_appdb_migration.py
tests/test_zcl.py
zigpy/appdb.py
zigpy/appdb_schemas/schema_v6.sql
zigpy/appdb_schemas/schema_v7.sql
zigpy/zcl/__init__.py

Keep track of unsupported attributes on a cluster. If for a `read_attributes` or `configure_attributes` requests, some of the attributes fail to be processed with a `UNSUPPORTED_ATTRIBUTE` ZCL status, then store this attributes. Next time, application can change its behavior based on what attributes are supported.
For example, if the "apparent power" attribute is not supported, then there's no need to create a sensor entity for this attribute.

Keep track of unsupported attributes on a cluster

---

zigpy/state.py

An attempt was made to address https://github.com/zigpy/zigpy-znp/pull/85 comments
@puddly for visibility. Would something like this work for ZNP?

Add a neighbor field in NetworkState object

---

tests/test_ota_provider.py
zigpy/ota/provider.py

Fix Ledvance OTA by accounting for new JSON version keys

---

tests/test_types.py
zigpy/types/named.py

Makes `KeyData` behave like `EUI64`.
Before:
```Python
Key(key=[91, 231, 111, 247, 2, 144, 217, 203, 87, 138, 85, 134, 119, 39, 1, 242], tx_counter=0, rx_counter=0, seq=0, partner_ieee=ff:ff:ff:ff:ff:ff:ff:ff)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
After:
```Python
Key(key=5b:e7:6f:f7:02:90:d9:cb:57:8a:55:86:77:27:01:f2, tx_counter=0, rx_counter=0, seq=0, partner_ieee=ff:ff:ff:ff:ff:ff:ff:ff)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Implement `__repr__` and `convert` for the `KeyData` type

---

zigpy/zcl/clusters/measurement.py

In #843 I noticed that couple of cluster definitions do not exist, and are just a `#TODO` comments. Here is the simple blind implementation. Not yet tested, as I'm not sure how to easily do it on the live HA instance, and will probably need to set up testing one, which I don't have time now.

Implement missing clusters

---

tests/test_zdo.py
zigpy/zdo/__init__.py

Refactor `ZDO` class to provide events for all incoming ZDO messages in addition to "old" events. This offers more flexibility for the radio libraries and/or application to react to ZDO messages.
In addition, split zigpy handled ZDO messages into separate class methods.

Provide ZDO events

---

zigpy/zcl/clusters/general.py

Fixes #881.
There's currently no nice way to represent a type with "special" values, even though many types actually have special "invalid" values already:
- `0xFF` for `bool`
- `0xFF` for `uint8` and `enum8` (!)
- same for uint16, 32, etc.
- Strings of length `0xFF`
- Arrays with length `0xFFFF`

Use correct datatype for `start_up_current_level` attribute

---

README.md

Replaces PR https://github.com/zigpy/zigpy/pull/863
Update the OTA section in README.md to read "LEDVANCE/OSRAM" and "SALUS/Computime" instead of "LEDVANCE" and "SALUS" to clarify that both brands are supported.
LEDVANCE and OSRAM "SMART+" brand of Zigbee devices are actually the same products, and SALUS devices are sometimes sold in boxes as Computime branded devices.

LEDVANCE is OSRAM and SALUS is Computime for OTA

---

.pre-commit-config.yaml
tests/test_types.py
zigpy/types/basic.py

Black was broken by a new Click release (https://github.com/psf/black/issues/2964) and CI is currently broken for all zigpy projects that rely on it.

Upgrade pre commit deps to fix CI failing

---

zigpy/__init__.py

The GitHub release defaulted to the `dev` branch so 0.44.0 was actually `dev@0.45.0.dev0`, not `master` 🤦

Bump master version to 0.44.1 to properly re-release

---

zigpy/zcl/clusters/closures.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/homeautomation.py
zigpy/zcl/clusters/lighting.py

There were a small handful of typos in the ZCLR7 PR, one of which is currently affecting quirks `hue(setp_mode=...)`.

Fix typos in ZCL schemas

---

tests/test_struct.py
zigpy/types/struct.py

This will be used to generate partial matches for device automation triggers in quirks, without having to define separate constants for `"step"` or `"step_mode"`:
```Python
>>> from zigpy.zcl.clusters.general import LevelControl
>>> step = LevelControl.commands_by_name["step"].schema  # this should be improved
>>> step(step_mode=0).as_dict(skip_missing=True)
{'step_mode': <StepMode.Up: 0>}
```

Add a `skip_missing` kwarg to the `as_` methods of `Struct` objects

---

tests/test_struct.py
tests/test_zcl_clusters.py
zigpy/zcl/clusters/general.py

Implement OTA frame control fields

---

tests/test_ota_provider.py
zigpy/ota/provider.py

Use the Ledvance OTA image versions to pick only the latest images

---

tests/test_device.py
zigpy/device.py

Related to https://github.com/home-assistant/core/issues/69893

Do not return the radio library status code when `expect_reply` is false

---

.github/workflows/ci.yml
setup.py
tests/test_zigbee_util.py
zigpy/types/named.py
zigpy/types/struct.py
zigpy/util.py

Fixes https://github.com/home-assistant/core/issues/70350.
https://github.com/zigpy/zigpy/discussions/972#discussion-4027315
This change also adds slightly more lenient parsing to any object with a `convert` method:
```Python
In [9]: t.KeyData.convert("AA:BB:CC:DD:EE:FF:AA:BB:CC:DD:EE:FF:AA:BB:CC:DD")
Out[9]: aa:bb:cc:dd:ee:ff:aa:bb:cc:dd:ee:ff:aa:bb:cc:dd
In [10]: t.KeyData.convert("AABBCCDDEEFFAABB CCDDEEFFAABBCCDD")
Out[10]: aa:bb:cc:dd:ee:ff:aa:bb:cc:dd:ee:ff:aa:bb:cc:dd
```

Replace PyCryptodome with Cryptography

---

tests/async_mock.py
tests/test_appdb.py
tests/test_appdb_migration.py
tests/test_device.py
zigpy/appdb.py
zigpy/appdb_schemas/schema_v8.sql
zigpy/application.py
zigpy/device.py

`last_seen` will now be persisted in the database and loaded on startup.
I've also added a runtime check to `_migrate_tables` to ensure that all "old" tables are explicitly specified in the migration. This will protect against migrations that accidentally leave out a new table introduced in an earlier migration (like I almost did when making this PR 😃).

Persist `Device.last_seen` in the database

---

tests/test_appdb.py
tests/test_device.py
zigpy/appdb.py
zigpy/device.py

0.45.0 changed the data type of `last_seen` to `datetime`. This PR reverts it back to a `float`.

Make sure `Device.last_seen` is still a float

---

tests/test_appdb.py
tests/test_appdb_migration.py
zigpy/appdb.py

The existing unit tests did not test the `last_seen` updating for an existing device, only that the value for a new join persisted. The SQL query was incorrect but because SQLite doesn't really have strong types, it has no problem with supplying the wrong data type in an `UPDATE` query.
This PR also preserves the previous behavior of having `last_seen = None` when the device was never seen.

Fix invalid SQL query with latest `last_seen` changes and add more thorough unit tests

---

zigpy/util.py

This improves error logging by logging the `repr` of the exception as opposed to its string (since `str(Exception()) == ''`) and by always logging the full traceback at the `DEBUG` level.

Log the entire listener exception traceback when an error occurs

---

tests/databases/simple_v8.sql
tests/test_appdb_migration.py
zigpy/appdb.py
zigpy/appdb_schemas/schema_v9.sql

I had the mistaken assumption that SQLite's `REAL` was a four byte float (as opposed to Python's 8 byte double), which would lose quite a bit of precision when storing large timestamps.  This is not the case and Python floats can be safely stored in an SQLite database.

Migrate `last_seen` to SQLite's `REAL` data type

---

tests/test_application.py
zigpy/application.py

Network information should be loaded from the stick after a network is formed. Otherwise, it will be inaccurate for a fresh ZHA installation with a new coordinator.

Load network information after forming a new network

---

.github/workflows/ci.yml

The V1 action was apparently sunset in February: https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1

Use the V2 Codecov uploader

---

tests/test_appdb.py
tests/test_appdb_migration.py
zigpy/appdb.py

Fixes https://github.com/home-assistant/core/issues/73067
SQLite allows the application to configure its journal file behavior (https://www.sqlite.org/pragma.html#pragma_journal_mode). The current behavior is to delete the `-journal` file every time a transaction completes, but we instead can just truncate the file and then delete it on shutdown.
Related issue: https://github.com/coleifer/pysqlite3/issues/41
See also: https://bugs.chromium.org/p/chromium/issues/detail?id=118470

Truncate the SQLite journal file instead of deleting it

---

zigpy/ota/provider.py

Correction from PR #991, need to stick with int but specify base 16 instead of base 10 due to the firmware check using the hex value instead of the previously expected 1.11, etc value from the sw_build_id.

Fix/Update to #991, Inovelli OTA configuration

---

tests/test_zcl.py
zigpy/zcl/__init__.py

Fixes #1018
I'm a little wary of merging this change without more runtime testing, especially with quirks. Are there any known devices that rely on the current behavior to work properly?

Set the request header's `direction` bit according to the cluster type

---

tests/test_application.py
zigpy/application.py

If an adapter breaks and loses network information (or is re-flashed), restore the most recent network backup instead of forming a brand new network.
This seems like a more sensible default than randomly generating settings.

Automatically restore the most recent network backup instead of forming a new network

---

zigpy/application.py

Logging currently strips the traceback, making it pretty useless for debugging.

Log the full traceback when one occurs during startup

---

zigpy/application.py

Backups were being performed every 24 minutes, not 24 hours...

Use the correct time period multiplier for the backup interval

---

setup.py

Allows you to do `pip install zigpy` on Python 3.7.

Allow installation on Python 3.7

---

requirements_test.txt
tests/test_appdb.py
zigpy/appdb.py

- switches the journal to WAL mode (big change)
- optimizes a few common queries to not perform writes unnecessarily (minor change)
Should address https://github.com/home-assistant/core/issues/77049
I've also reduced the frequency with which `last_seen` timestamps are updated per-device to once every 30s. In theory this can cause `last_seen` to roll backwards if the value is cached somewhere and then zigpy is restarted.

Reduce DB filesystem writes

---

tests/test_backups.py
zigpy/backups.py

Cherry picked from https://github.com/zigpy/zigpy/pull/1037.
ZHA is currently using this kwarg but it's not in the latest zigpy release...

Add a `create_new` kwarg to `BackupManager.restore_backup`

---

zigpy/application.py
zigpy/config/__init__.py
zigpy/config/validators.py

This PR adds a configuration option to allow adding additional endpoints.
This is required for xbee end devices as they require 0xE6 and 0xE8 endpoints and by default zigpy ignores those.
Example configuration.
```
zha:
zigpy_config:
additional_endpoints:
- endpoint: 0xE6
profile: 0xC105
device_type: 0x0000
device_version: 0b0000
input_clusters: []
output_clusters: [0x21]
- endpoint: 0xE8
profile: 0xC105
device_type: 0x0000
device_version: 0b0000
input_clusters: []
output_clusters: [0x21]
```

Add additional endpoint configuration option

---

tests/test_zcl_clusters.py
zigpy/types/struct.py
zigpy/zcl/clusters/general.py

Fixes #1046.
The error in the linked issue is due to unit tests mocking out the request entirely, so the line had coverage but was never actually tested. The correct behavior is for zigpy to send an `ABORT` status.

Implement the full OTA `image_block_response` structure

---

tests/test_quirks.py
zigpy/quirks/__init__.py
zigpy/util.py
zigpy/zcl/clusters/general.py

Quirks currently do not pass through command keyword arguments, leading to strange errors with quirked devices.

Handle request keyword arguments in quirks

---

tests/test_types.py
zigpy/types/basic.py

Makes implementing numerical form fields in ZHA possible without having to compute these values directly:
```python
>>> import zigpy.types as t
>>> t.uint8_t.min_value
0
>>> t.uint8_t.max_value
255
>>> t.int16s.min_value
-32768
>>> t.int16s.max_value
32767
```

Expose `min_value` and `max_value` on integer types

---

tests/test_application.py
zigpy/application.py

Some devices incorrectly address packets to coordinator endpoint 0. #1043 did not handle this correctly.

Handle devices sending non-ZDO packets to endpoint 0

---

tests/test_struct.py
zigpy/types/struct.py

This will allow for structs to be constructed from dictionaries and vice versa, allowing for complex commands to be sent via ZHA's cluster API.

Add a recursive `Struct.to_dict` and a `Struct.from_dict` method

---

tests/test_zcl.py
zigpy/zcl/__init__.py

`direction` is used by both the zigpy-internal `_create_request` and commands like `Color.move_to_hue`.
https://github.com/home-assistant/core/issues/79808

Internally pass schema `args` and `kwargs` without expansion to avoid collisions

---

.github/workflows/ci.yml
tests/test_zdo.py
zigpy/zdo/__init__.py

Packets with a destination endpoint of `0` are attempted  to be deserialized as ZDO. If they are not in fact ZDO, deserialization is expected to fail and the packet is passed along, but an unnecessary warning is logged.
```Python
ZigbeePacket(src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x5C94), src_ep=2, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=0, source_route=None, extended_timeout=False, tsn=29, profile_id=260, cluster_id=64561, data=Serialized[b'\x15/\x12\n$\x10'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=255, rssi=-58)
```

Allow ZDO deserialization to fail without logging a warning

---

tests/test_zcl_foundation.py
zigpy/zcl/clusters/closures.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/homeautomation.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/clusters/lighting.py
zigpy/zcl/clusters/measurement.py
zigpy/zcl/clusters/protocol.py
zigpy/zcl/clusters/security.py
zigpy/zcl/clusters/smartenergy.py
zigpy/zcl/foundation.py

Adds a new `access` enum flag and a boolean `mandatory` flag for all ZCL cluster attributes. This should give ZHA more information about which attributes can be read from Home Assistant's web interface.
```python
In [1]: from zigpy.zcl.clusters.general import AnalogInput
In [2]: AnalogInput.attributes_by_name["status_flags"].access
Out[2]: <ZCLAttributeAccess.Report|Read: 9>
In [3]: AnalogInput.attributes_by_name["status_flags"].mandatory
Out[4]: True
```

Add `access` and `mandatory` fields to ZCL attribute definitions

---

tests/test_device.py
zigpy/device.py
zigpy/types/basic.py

Alternative to https://github.com/zigpy/zigpy-znp/pull/190 that also fixes https://github.com/home-assistant/core/issues/80519. The below screenshot shows that an offline device is considered unavailable after this change when used with a ZNP coordinator:
I believe the vast majority of packets are going to be a request/reply pair, or are themselves unsolicited updates from a device. The only devices I'm aware of that would fall back to explicit `Basic` cluster polling are devices like King of Fans controllers, which do not generate a ZCL default response.

Only update `last_seen` on RX

---

tests/test_application.py
zigpy/application.py

I think the current logic may be inverted. Instead, how about:
- If a packet will be receiving a reply, we know when it was not received because no response was sent by the recipient.
- If a packet will *not* be receiving a reply, we will have no way to know when it sends successfully, so we should enable APS ACKs to receive a low-level response from the device.
Thoughts?
Probably will fix https://github.com/home-assistant/core/issues/81057, since the Conbee struggles with APS ACKs it seems.

Only enable APS ACKs for packets without implicit delivery notification

---

tests/ota_providers/test_ota_provider_inovelli.py
zigpy/ota/__init__.py
zigpy/ota/provider.py

Updates as Inovelli has added the image_type and manufacturer_id fields to their firmware.json file. This removes the workaround present using the model instead of the image_type and enables users to push firmware both locally and direct from Inovelli.

Updates to the Inovelli OTA config

---

tests/test_appdb.py
tests/test_zcl.py
zigpy/appdb.py
zigpy/zcl/__init__.py

This PR removes unsupported attributes if they become supported in the future. This can be from a firmware update or a quirk update etc. 
~~@puddly let me know if you want to do this differently. I think I covered everything. I have an outstanding note in one of the tests for something that is a bit confusing.~~

Remove unsupported attributes when they become supported

---

zigpy/types/basic.py

Python 3.11 made the `enum.IntFlag` class reusable, removing the need for our rebinding of private functions.

Python 3.11 compatibility

---

setup.py
zigpy/serial.py

This call can sometimes stall forever if the radio is inaccessible.

Add a timeout to `loop.create_connection`

---

tests/test_appdb_migration.py
tests/test_application.py
zigpy/device.py

The `zigpy.neighbors` module is gone so ZHA will not be able to start up anyways and will need to be fixed.

Remove ZHA `neighbors` compatibility object

---

tests/test_topology.py
zigpy/topology.py

https://github.com/zigpy/zigpy/pull/1099 removed a feature required by zigpy-deconz

Allow scanning the topology of specific devices

---

tests/ota_providers/test_ota_provider_thirdreality.py
zigpy/ota/provider.py

A `versions` key appears to have been added on November 9th, two days after we merged the zigpy PR.
@hwzolin

Account for new ThirdReality OTA JSON format

---

setup.cfg
tests/conftest.py
tests/test_appdb.py
tests/test_appdb_migration.py
tests/test_application.py
tests/test_backups.py
tests/test_topology.py
tests/test_zdo.py
zigpy/application.py

Unit tests were mocking too much of `Device` to actually catch this error.
I'd like to slowly start migrating unit tests to use fewer mocks and real objects (or at the very least `spec_set`).

Fix device end device removal error with new topology code

---

tests/test_types.py
zigpy/types/basic.py

There are several places where we can replace workarounds and reimplementations with a central implementation of big endian types.
[Example1](https://github.com/zigpy/zha-device-handlers/blob/31245e0e3643c5011be849a4ebbda39a5eb379e6/zhaquirks/tuya/__init__.py#L129)
[Example2](https://github.com/zigpy/zha-device-handlers/blob/790c90b2bf490345d959776abaa03abb515da785/zhaquirks/xiaomi/aqara/feeder_acn001.py#L148)
[Example3](https://github.com/zigpy/zigpy-xbee/blob/dev/zigpy_xbee/types.py#L33)

Add big endian int types

---

CONTRIBUTING.md

The Python version 3.7 in the example results in an error.
````
$ pip install -e '.[testing]'
...
ERROR: Package 'zigpy' requires a different Python: 3.7.16 not in '>=3.8'
````
Updating to 3.8 resolves this.

Update python version in CONTRIBUTING.md

---

tests/test_ota_validators.py
zigpy/ota/validators.py

Allows for `validate_ota_image` to be used to "validate" Hue OTA images.
The firmware itself is fully encrypted so it can't actually be validated.

Return `UNKNOWN` as a validation result for unknown OTA image types

---

tests/test_application.py
zigpy/application.py
zigpy/exceptions.py

Raises `TransientConnectionError` for errors that likely will resolve themselves after retrying (currently just `ENETUNREACH`). 
https://github.com/home-assistant/core/pull/84615

Raise a useful exception on transient connection errors

---

tests/test_appdb_migration.py
zigpy/appdb.py
zigpy/exceptions.py

Basically, we now enforce `PRAGMA user_version = 12` and `devices_v12`. If they don't sync up, something is broken and we shouldn't let zigpy start up and break the database further.
There is a small chance of data loss if `user_version` is ever cleared. To ensure this doesn't happen, I think it is best to explicitly fail on startup when the versions are inconsistent.
Downgrades are still permitted so this will be a breaking change only for people using very corrupted databases.
---
Side note: should we similarly fail to start up when `PRAGMA integrity_check` fails? We currently log an error but I'm sure many people still run HA and ignore it. We would need a way to fix the database, though, and the method in https://github.com/zigpy/zigpy-cli#database isn't guaranteed to work (though has …

Fail loading the database when table suffixes aren't consistent with `user_version`

---

tests/test_zcl_foundation.py
zigpy/zcl/foundation.py

This catches `ZCLCommandDef` definitions that use tuples. This isn't supported.

Ensure ZCL command schemas do not directly use tuples

---

setup.py
tests/test_serial.py
zigpy/serial.py

We can just use `urllib.parse.urlparse`.

Remove unnecessary `yarl` dependency

---

setup.py

It's currently only included implicitly by `aiohttp`, even though we directly import it.

Explicitly include `attrs` as a dependency

---

setup.py
tests/test_serial.py
zigpy/__init__.py
zigpy/serial.py

0.53.1 release
This release significantly simplifies packaging for https://github.com/NabuCasa/universal-silabs-flasher/pull/4, as yarl and aiohttp and its dependencies had no pure-Python wheels on PyPI. aiohttp isn't technically required to run zigpy but yarl was.

0.53.1 Release

---

.pre-commit-config.yaml
tests/async_mock.py
tests/ota_providers/test_ota_provider_inovelli.py
tests/ota_providers/test_ota_provider_ledvance.py
tests/ota_providers/test_ota_provider_salus.py
tests/ota_providers/test_ota_provider_sonoff.py
tests/ota_providers/test_ota_provider_thirdreality.py
tests/test_app_state.py
tests/test_application.py
tests/test_group.py
tests/test_ota_provider.py
tests/test_struct.py
zigpy/appdb.py
zigpy/quirks/registry.py
zigpy/util.py
zigpy/zcl/__init__.py

`isort` is breaking CI.
MyPy v0.990 introduced a change that causes it to fail to discover the type of `Basic.cluster_id` so we can't seem to use the most recent version.

Bump pre-commit dependencies

---

zigpy/application.py

Otherwise, ZHA will only retry three times before giving up.

Treat `ConnectionRefusedError` as a transient connection error

---

zigpy/ota/OTA_URLs.md
zigpy/ota/provider.py

Inovelli requested to update their OTA URL for zigpy. These changes are to update to the new json while they work on changing how they handle Zigbee OTA image update releases.

Inovelli OTA URL Changes

---

tests/conftest.py
zigpy/appdb.py

`aiosqlite.Connection.close` doesn't actually close the thread immediately. I've copied Home Assistant's global thread-leaking detection test to ensure this is caught in the future.

Wait for aiosqlite connection thread to join before shutting down

---

tests/test_application.py
zigpy/application.py

They will only be treated as such when then NWK address changes. Otherwise, nothing should happen (because no device info changed). Mainly affects bellows, as it passes through stack-generated ZDO responses back to the application.

Do not treat IEEE address responses as rejoins

---

tests/test_appdb.py
zigpy/appdb.py

The quirk for the affected Tuya device removes an endpoint but the attribute cache must have been built with an earlier revision of the quirk (or an unquirked device), causing a startup error.
Related to https://github.com/home-assistant/core/issues/89245#issuecomment-1465290171, fixes a few more issues of this type.

Don't assume all endpoints will exist when loading unsupported attrs

---

setup.py
zigpy/application.py
zigpy/device.py

The cancellation semantics of `asyncio.wait_for` are probably the root cause of the task cancellation bug (#809). zigpy-znp has always used `asyncio.timeout` internally without any problems so we may as well migrate zigpy as well. Plus, the context manager syntax is usually clearer.
https://github.com/python/cpython/pull/98518

Use `asyncio.timeout` instead of `asyncio.wait_for`

---

tests/test_application.py
zigpy/application.py

There are a few other types of connection errors that we don't handle:
```
│    ├── ConnectionError
│    │    ├── BrokenPipeError
│    │    ├── ConnectionAbortedError
│    │    ├── ConnectionRefusedError
│    │    └── ConnectionResetError
```

Treat all connection errors as transient

---

ruff.toml
tests/test_listeners.py
zigpy/application.py
zigpy/listeners.py
zigpy/util.py

RUF006: Store a reference to the return value of asyncio.create_task
Ref: https://beta.ruff.rs/docs/rules/asyncio-dangling-task/

Always store a reference to task objects

---

tests/test_application.py
zigpy/application.py
zigpy/const.py
zigpy/exceptions.py

Mostly for the Conbee. Currently, what happens is this:
```Python
2023-04-10 18:52:58.538 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ConBee II for zha
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
result = await component.async_setup_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 122, in async_setup_entry
await zha_gateway.async_initialize()
File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 220, in async_initialize
raise exc
File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 205, in async_initialize
self.application_controller = await app_controller_cls.new(
File …
```

Start up even when the `permit(0)` broadcast fails due to interference

---

zigpy/application.py

It appears that the energy scan happening at the same time as a backup can cause issues with some coordinators, namely EmberZNet multi-PAN.

Perform the startup energy scan synchronously, before starting backups

---

tests/test_application.py
zigpy/application.py

Accidentally introduced in #1183

Do not create a new backup when forming a fast temporary network

---

tests/test_application.py
zigpy/application.py

See #1185 (@dumpfheimer).
Currently, ZNP implements the best version of this API because it allows the coordinator to change channels after having a few chances to send out the broadcast. Other coordinators (EZSP and deCONZ) directly react to the loopback request and migrate almost immediately.
This rudimentary version has been implemented in zigpy-cli for some time and has been used by a few people to migrate their networks. From what I can tell, if an end device does not react to the channel change broadcast, it definitely won't with a unicast request. But it still might find the network again after detecting that it has been orphaned.
Thoughts?

Implement an API to change channels

---

setup.cfg
setup.py
tests/test_quirks.py
zigpy/__init__.py
zigpy/appdb_schemas/__init__.py
zigpy/application.py
zigpy/config/__init__.py
zigpy/config/defaults.py
zigpy/const.py
zigpy/endpoint.py
zigpy/ota/__init__.py
zigpy/ota/image.py
zigpy/ota/provider.py
zigpy/profiles/__init__.py
zigpy/profiles/zha.py
zigpy/profiles/zll.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py
zigpy/state.py
zigpy/topology.py
zigpy/types/__init__.py
zigpy/types/named.py
zigpy/types/struct.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py

Uses https://github.com/Instagram/MonkeyType to dynamically collect type annotations at runtime. We use the new union syntax, so you'll need to install an updated version of the code parsing library used by MonkeyType:
```bash
pip install MonkeyType
pip install git+https://github.com/hauntsaninja/LibCST@pep604apply
```
Then, run Home Assistant with the modules you want to trace:
```bash
MONKEYTYPE_TRACE_MODULES=zigpy,bellows,zhaquirks,homeassistant monkeytype run -m homeassistant
```
After you use Home Assistant (it will be extremely slow!) and run through all of the codepaths, cleanly quit Home Assistant. It will take about 10-20 minutes to generate a multi-gigabyte `monkeytype.sqlite` file in the current folder.
You can then apply annotations to a specific module:
```bash …
```

More type annotations

---

tests/test_quirks.py
zigpy/quirks/__init__.py

Ensures https://github.com/home-assistant/core/blob/4de124cdd5586c566db7351400e8cabd3d3075bc/homeassistant/components/zha/binary_sensor.py#L171-L174 works for devices with quirks.

Ensure constant attributes can be read with `.get`

---

tests/test_struct.py
zigpy/endpoint.py
zigpy/group.py
zigpy/types/struct.py

`hasattr(self._device.application, "_dblistener")` is not enough to check if a DB listener is attached (since the attribute will always exist, it can just be `None`).

Remove unnecessary or incorrect uses of `hasattr`

---

tests/test_quirks.py
tests/test_zcl.py
zigpy/zcl/__init__.py

This will break a few of ZHA's unit tests but it exposes a bunch of bugs, including https://github.com/puddly/core/commit/4de50036f364380ec5d9745d5e1c1cf4de026b7d#r110865576.

Fail when an unknown attribute is read with `.get()`

---

tests/test_appdb.py
tests/test_zcl.py
zigpy/appdb.py
zigpy/appdb_schemas/schema_v12.sql
zigpy/zcl/__init__.py

This will allow ZHA to more intelligently decide which devices need to be polled on startup. I would like to make the default behavior not overload the network with requests, with an optional setting to re-enable the old behavior for people who turn off bulbs.
Exposing this information will require some sort of new attribute API, since accessing private dictionaries is not a good one.
---
In the future, I think it would be useful to have some sort of unified proxy for attribute polling/subscriptions:
```Python
await self.subscribe_to_attribute("attr_name", min=5, max=30, delta=1, callback=self.attr_updated)
```
This can then automatically setup attribute reporting (if necessary) and resort to polling when a device does not report in the expected time period.

Keep track of the last updated time of attributes

---

tests/test_struct.py
zigpy/types/basic.py

Allow enum parsers to parse the string value of the enum name not only int value.
When enum entries are displayed in HA UI, it will display the stringified version of the enum. The enum should be possible to reproduce from the given name.
This was changed in https://github.com/zigpy/zigpy/pull/352

Allow enum to parse enum value

---

tests/test_endpoint.py
zigpy/endpoint.py

Looks like some devices erroneously have a `Groups` cluster (0x0004) but do not actually support any commands.
Maybe we should raise a `zigpy.exceptions.UnsupportedCommand` error instead of returning the response?
Fixes #1210

Handle `UNSUP_CLUSTER_COMMAND` when scanning groups

---

zigpy/profiles/__init__.py
zigpy/profiles/zgp.py
zigpy/profiles/zha.py

This will allow enumerations of greenpower clusters in ZHA quirks.
Ref: https://zigbeealliance.org/wp-content/uploads/2019/11/docs-09-5499-26-batt-zigbee-green-power-specification.pdf (page 73)

Add greenpower cluster enumerations

---

tests/test_zcl.py
tests/test_zigbee_util.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/quirks/__init__.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zdo/__init__.py

The decorator-added keyword arguments are pretty confusing and break with inheritance. It's more straightforward for the downstream application to handle these kinds of retries on its own in one spot.
One side effect of this change is a consolidation of retries: the only place they are done in zigpy is during device initialization, which is now retried five times instead of three. This is because during each retry, the node descriptor request also was retried a few times implicitly.
Related: https://github.com/home-assistant/core/issues/93955

Remove retryable and `tries` + `delay`

---

tests/test_topology.py
zigpy/topology.py

Apparently unit tests have again too many mocks and allowed this typo to sneak in.

Remove `tries` from topology function calls

---

tests/conftest.py
tests/ota_providers/test_ota_provider_remote.py
zigpy/config/__init__.py
zigpy/ota/__init__.py
zigpy/ota/provider.py

Implements the format specified in https://github.com/zigpy/zigpy/wiki/OTA-Information-for-Manufacturers:
```yaml
zha:
zigpy_config:
ota:
remote_providers:
- url: "https://fw.zigbee.example.org/ota.json"
manufacturer_ids: [0x1234, 0x5678]
- url: "https://fw.zigbee.example.org/ota-beta.json"
```
This allows for new providers to be added to zigpy without extra code.  This also allows for manufacturers to distribute test feed URLs to customers without deploying them globally.

Generic OTA providers
