zigpy/zigpy

tests/test_zcl_clusters.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py

The time cluster is using the general request.

Handle cluster general request

---

tests/test_zcl_foundation.py
zigpy/types/basic.py
zigpy/zcl/foundation.py

Add support for ZCL collection types

---

tests/test_zdo.py
zigpy/zdo/__init__.py

Ensure zdo reply coro is run

---

setup.py

Fix:
https://github.com/home-assistant/hassio/issues/383
https://github.com/home-assistant/home-assistant/issues/12675

Don't use unmaintained security library

---

zigpy/quirks/xiaomi/__init__.py

OnOffCluster of Xiaomi Open/Close Sensor should be an output cluster.

Move OnOffCluster from in_cluster to out_cluster

---

zigpy/zcl/clusters/closures.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/homeautomation.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/clusters/lighting.py
zigpy/zcl/clusters/protocol.py
zigpy/zcl/clusters/security.py
zigpy/zcl/clusters/smartenergy.py
zigpy/zdo/types.py

update cluster attributes to bitmap8, bitmap16 etc

Update cluster attributes to bitmapXX where applicable.

---

zigpy/zdo/types.py

Adds support for requesting the neighbor and routing tables from a Zigbee device.

Add support for Mgmt_Lqi_req and Mgmt_Rtg_rsp

---

zigpy/quirks/__init__.py
zigpy/quirks/keen/__init__.py

This PR adds support for Keen Home temperature and humidity sensor (https://keenhome.io/products/temp-sensor).

Add Support for Keen Home Temp and Humidity Sensor

---

README.md

@rcloran As per #86  updated the zigpy README.md with another link and a further extended description.
Also included a link to a library deconz from for @Equidamoid which should work with zigpy.

Updated README.md with another link and a further extended description

---

zigpy/zcl/clusters/general.py

Add OnOff cluster server commands schema to confirm ZCL specification revision 6.

Add schema to zcl.clusters.general.OnOff server commands.

---

zigpy/quirks/ikea/__init__.py

Remove LevelControl input cluster.

Fix Ikea Tradfri plug input clusters

---

zigpy/quirks/__init__.py

Fix imports in quirks to prevent circular import issues. See #117

Fix imports in quirks

---

zigpy/profiles/zha.py

Add Zigbee Thermostat DeviceType to ZHA profile.

Add DeviceType.THERMOSTAT

---

zigpy/appdb.py

Restore attributes from cache before and after applying quirks.

Restore attributes before and after applying quirks

---

zigpy/endpoint.py

Addresses https://github.com/home-assistant/home-assistant/issues/20980#issuecomment-480497419 comment

Log unknown cluster messages at debug level.

---

README.md

Added the xbee3 and s2 to the list of supported modules.

Add additional supported xbee modules

---

tests/test_quirks.py
zigpy/endpoint.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/lightlink.py

Update Liglink cluster schema.
Use ZHA profile for utility commands (0x40 -- 0xff) of the LightLink
cluster.

Update ZLL Commissioning cluster schema.

---

tests/test_appdb.py
tests/test_device.py
tests/test_endpoint.py
tests/test_group.py
zigpy/appdb.py
zigpy/device.py
zigpy/endpoint.py
zigpy/group.py

Address comments in https://github.com/zigpy/zigpy/pull/156#issuecomment-492697739

Use endpoints as group members.

---

zigpy/zcl/clusters/hvac.py

Fix hvac.Thermostat attribute typo.

---

zigpy/zcl/clusters/lightlink.py

Fixes `touchlink` cluster commands schema.

Fix touchlink cluster schema.

---

zigpy/zcl/clusters/closures.py

Fix DoorLock cluster attributes schema.

Fix DoorLock attributes schema.

---

zigpy/zdo/types.py

Use NWK class for mgmt_lqi_rsp & mgmt_rtg_rsp response parameters schema.

ZDO Schema updates.

---

zigpy/device.py

Store Device's NWK address as an NWK class instance.

Update device.Device() nwk property.

---

tests/test_zcl_foundation.py
tests/test_zdo_types.py
zigpy/__init__.py
zigpy/device.py
zigpy/quirks/__init__.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

0.7.0 Release.

---

zigpy/quirks/registry.py

Don't reapply a quirk to a device that has already had a quirk applied to it.

Don't quirk quirked devices

---

zigpy/__init__.py
zigpy/quirks/registry.py

0.7.1 Release.

---

tests/test_zcl.py
tests/test_zcl_foundation.py
zigpy/endpoint.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py

- Refactor ZCL serialization/deserialization.
- allow "Disable Default Response" bit control
- Disable default response for "replies"
Fixes #208

Refactor ZCL serialization/deserialization.

---

zigpy/appdb.py

No need to load the entire attribute cache if the cluster would be replaced by a quirk.

Load manufacturer/model attributes only before applying quirks.

---

tests/test_zcl_clusters.py
zigpy/zcl/clusters/security.py

Update IAS Cluster schema.

---

tests/test_endpoint.py
zigpy/__init__.py
zigpy/endpoint.py
zigpy/quirks/__init__.py
zigpy/zcl/__init__.py

0.7.2 Release.

---

zigpy/application.py
zigpy/device.py

Indicate to `ControllerApplication.request()` whether it is a request or a reply.

Add expect_reply parameter back.

---

tests/test_appdb.py
tests/test_device.py
tests/test_endpoint.py
tests/test_zcl.py
tests/test_zdo.py
tests/test_zdo_types.py
zigpy/device.py
zigpy/endpoint.py
zigpy/zcl/__init__.py
zigpy/zdo/__init__.py
zigpy/zdo/types.py

Remove bad hack

---

tests/test_application.py
zigpy/application.py
zigpy/types/named.py

Allow radios to update Zigbee network parameters.

Allow Zigbee network parameters update.

---

zigpy/application.py

Use zigpy.types.EUI64 for ieee in handle_join().

Use zigpy.types.EUI64 for ieee.

---

README.md
tests/test_appdb.py
tests/test_application.py
tests/test_device.py
tests/test_endpoint.py
tests/test_types.py
tests/test_zcl.py
tests/test_zcl_foundation.py
tests/test_zdo.py
tests/test_zdo_types.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/types/basic.py
zigpy/types/named.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py
zigpy/zdo/__init__.py
zigpy/zdo/types.py

0.10.0 Release.

---

tests/test_zigbee_util.py
zigpy/util.py

Fix install code CRC endiness.

---

tests/test_zcl_foundation.py
zigpy/types/basic.py
zigpy/zcl/foundation.py

allows things like:
```
import zigpy.types as t
List = t.List(t.uint8_t)
my_list = List([1, 2, 4, 5])
my_list.serialize()
```

Re-instantiate list items for serialization.

---

.travis.yml
tox.ini

Drop Python 3.5, add py38 to test suite.

Drop support for py35.

---

.github/release-drafter.yml
.github/workflows/release-management.yml

Use https://github.com/apps/release-drafter for release notes drafting.

Adopt release management drafter.

---

.github/release-drafter.yml
.github/workflows/release-management.yml
.travis.yml
README.md
setup.py
tests/test_application.py
tests/test_group.py
tests/test_zcl_foundation.py
tests/test_zigbee_util.py
tox.ini
zigpy/__init__.py
zigpy/application.py
zigpy/group.py
zigpy/types/basic.py
zigpy/types/named.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py
zigpy/zdo/__init__.py

0.11.0 Release.

---

tests/test_group.py
zigpy/group.py

We shouldn't iterate over the same dict we're modifying.

Fix group removal.

---

tests/test_appdb.py
zigpy/appdb.py
zigpy/application.py
zigpy/device.py
zigpy/types/named.py

Device() class to hold "relays" list for static routing.
Save relay list updates to database.

Static routing framework.

---

tests/test_application.py

Tests cleanup

---

setup.py
tests/test_application.py
zigpy/application.py

Add configuration dict using voluptuous schema validation.

Add configuration dict option

---

zigpy/zcl/clusters/lighting.py

- Add "Move Color Temperature"
- Add "Step Color Temperature"
commands of the Color control cluster.

Add missing color cluster commands

---

tests/test_ota_provider.py
zigpy/ota/image.py
zigpy/ota/provider.py

OTA cleanup.

---

tests/test_appdb.py
zigpy/group.py

Don't auto remove groups with no members.

Don't auto remove empty groups

---

zigpy/appdb.py

Update DB schema to use foreign keys.

Refactor SQL DB schema

---

zigpy/zdo/types.py

ZDO `Parent_annce` command schema.

Add ZDO Parent_annce commands

---

README.md
tests/test_appdb.py
tests/test_ota_provider.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/group.py
zigpy/ota/__init__.py
zigpy/ota/image.py
zigpy/ota/provider.py
zigpy/zcl/clusters/lighting.py
zigpy/zdo/types.py

0.13.0 Release

---

README.md

Update README.md with specific ZiGate radio modules as per https://github.com/doudz/zigpy-zigate/blob/master/README.md

Update README.md with specific ZiGate radio modules

---

README.md
tests/test_device.py
tests/test_quirks.py
zigpy/__init__.py
zigpy/device.py
zigpy/quirks/__init__.py

0.13.1 Release

---

tests/test_appdb.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/zcl/__init__.py

0.13.2 Release

---

README.md

Update README.md with PyPI link to zigpy-cc
https://pypi.org/project/zigpy-cc/

Update README.md with PyPI link to zigpy-cc

---

tests/test_zigbee_util.py
zigpy/device.py
zigpy/endpoint.py
zigpy/group.py
zigpy/ota/provider.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zdo/__init__.py

Refactor LoggerMixin class

---

zigpy/ota/provider.py

Refactor zigpy OTA provider logging

---

zigpy/appdb.py
zigpy/zcl/__init__.py

Fix zigpy.zcl.clusters circular imports

Fix zigpy.zcl.clusters circular imports

---

setup.py
tests/test_appdb.py
tests/test_application.py
tests/test_device.py
tests/test_endpoint.py
tests/test_group.py
tests/test_ota.py
tests/test_ota_provider.py
tests/test_zcl.py
tests/test_zcl_clusters.py
tests/test_zdo.py
tests/test_zigbee_util.py
tox.ini

Use asynctest for asyncio tests.

Use asynctest for asyncio tests.

---

tests/test_zdo.py
tests/test_zigbee_util.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py
zigpy/zdo/__init__.py

Catch exceptions when scheduling tasks in handlers.

---

tests/test_quirks.py
zigpy/zcl/__init__.py

Make `_attridx` a public attribute.

Make _attridx a public attribute

---

tests/test_zcl_clusters.py
zigpy/zcl/clusters/security.py

@Adminiuga I think I did this right... lmk if I have to update / change anything.

Add enums for IAS Ace cluster

---

tests/test_zcl.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py

Allow TSN override for both replies and requests.

Allow TSN override for zcl requests

---

tests/test_zcl.py
tests/test_zcl_clusters.py
zigpy/__init__.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/security.py
zigpy/zcl/foundation.py

0.16.0 Release

---

.travis.yml
tox.ini

Drop python3.6 support

---

zigpy/zcl/clusters/hvac.py

Implement some attributes of the FAN cluster as enums.

HVAC FAN cluster enums

---

tests/test_zcl_clusters.py
zigpy/zcl/clusters/general.py

Implement Enums of the basic cluster.

Update Basic cluster enums

---

zigpy/types/named.py
zigpy/zcl/clusters/closures.py
zigpy/zcl/clusters/general.py

Lock cluster enums

---

zigpy/exceptions.py

Add Exception for ControllerApplication and API layers. This allows underlying libraries to be more specific when throwing an exception for  specific cases (UART disconnect, Controller non responsive) which allows higher layer application to handle specific cases or just catch ZigbeeException.

Add new Exceptions

---

.github/workflows/publish-to-pypi.yml

GH Action to publish package

---

tests/test_zcl_clusters.py
zigpy/zcl/clusters/security.py

Refactor `security` clusters and use enums.

IAS enum refactor

---

.github/workflows/publish-to-pypi.yml
.travis.yml
tests/test_endpoint.py
tests/test_types.py
tests/test_zcl.py
tests/test_zcl_clusters.py
tests/test_zcl_foundation.py
tests/test_zdo_types.py
tox.ini
zigpy/__init__.py
zigpy/appdb.py
zigpy/endpoint.py
zigpy/exceptions.py
zigpy/ota/image.py
zigpy/profiles/zha.py
zigpy/profiles/zll.py
zigpy/types/basic.py
zigpy/types/named.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/closures.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/clusters/security.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

0.17.0 Release

---

zigpy/appdb.py

Restore device type for non ZHA/ZLL profiles.

Restore device type for non ZHA/ZLL profiles

---

tests/test_zcl_clusters.py
zigpy/zcl/clusters/hvac.py

Update HVAC enums

---

tests/test_zcl.py
zigpy/zcl/__init__.py

Update the content of the cache, on successful attribute writes.

Update cluster cache on successful attribute writes

---

tests/test_zigbee_util.py
zigpy/util.py

Make `catching_coro()` method publicly available.

Make `catching_coro()` method publicly available.

---

tests/test_zcl.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py

Add configure_reporting_multiple to allow configuration of multiple attributes in the same request.

Refactor configure_reporting commands.

---

.github/workflows/publish-to-pypi.yml
tests/test_quirks.py
tests/test_zcl.py
tests/test_zcl_clusters.py
tests/test_zcl_foundation.py
tests/test_zdo_types.py
tests/test_zigbee_util.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/quirks/__init__.py
zigpy/types/named.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/foundation.py

0.18.0 Release

---

tests/test_zcl_foundation.py
tests/test_zdo_types.py
zigpy/types/basic.py
zigpy/types/named.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

Implement APS Status enum
Implement NWK Status enum
Implement MAC Status enum

Add Status enums for lower layers.

---

tests/test_types.py
tests/test_zcl_foundation.py
tests/test_zdo_types.py
zigpy/__init__.py
zigpy/types/basic.py
zigpy/types/named.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

0.18.1 Release

---

tests/test_group.py
zigpy/group.py

Fake ZCL "default response" for multicast requests.

Fake ZCL "default response" for multicast requests

---

zigpy/quirks/__init__.py

Copy attributes like `last_seen`, `relays` for `CustomDevices`

Copy additional attributes for device quirks

---

tests/test_group.py
zigpy/__init__.py
zigpy/group.py
zigpy/quirks/__init__.py

0.18.2 Release

---

tests/test_appdb.py
tests/test_device.py
tests/test_endpoint.py
tests/test_group.py
zigpy/__init__.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/group.py

0.19.0 Release.

---

setup.py

Change module name back to zigpy.

Change module name back to zigpy

---

tests/test_ota.py
tests/test_ota_provider.py
zigpy/application.py
zigpy/ota/__init__.py
zigpy/ota/provider.py

Use schema for OTA initalization.

Refactor OTA initialization

---

tests/test_appdb.py
tests/test_application.py
zigpy/application.py

Require the library libs to implement the following methods:
- `shutdown()`
- `startup()`
- `request()`
- `permit_ncp()`

Requires specific methods to be implemented by all libs.

---

tests/test_appdb.py
tests/test_application.py
zigpy/appdb.py
zigpy/application.py
zigpy/config.py

Create ControllerApplication from async class method.

Create ControllerApplication from async class method

---

setup.py

Add long description to PyPi index.

Add long description to PyPi index

---

.coveragerc
tests/test_appdb.py
tests/test_application.py
tests/test_config.py
tests/test_ota.py
tests/test_ota_provider.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/application.py
zigpy/config.py
zigpy/ota/__init__.py
zigpy/ota/provider.py
zigpy/typing.py

Merge new zigpy initialization and schemas.

New zigpy initialization

---

README.md

Update README.md extending the "How to contribute" section with broadened but still generic suggestions on different ways to contribute.

Update README.md extending the "How to contribute" section

---

setup.py

Really add long description

---

tests/test_config.py
zigpy/config/__init__.py
zigpy/config/defaults.py

Replace defaults with None.
Add `TC_ADDRESS` -- trust center address parameter.

Refactor SCHEMA_NETWORK

---

tests/test_config.py
zigpy/config/__init__.py

Change SCHEMA_NETWORK validation

Change SCHEMA_NETWORK validation

---

README.md

Update README.md with new (old) link to PyPI project for zigpy

Update README.md with new (old) link to PyPI project for zigpy

---

zigpy/config/__init__.py

TC_ADDRESS should be an EUI64 address, not a key.

TC_ADDRESS should be an EUI64 address

---

tests/test_application.py
zigpy/application.py

ControllerApplication.config setter.
ConnterllerApplication.update_config() partial config update method.

Allow ControllerApplication configuration updates

---

README.md

Update README.md adding a troubleshooting section about debug logs from Home Assistant

Update README.md adding a troubleshooting section about debug logs from HA

---

README.md
tests/test_endpoint.py
tests/test_zcl.py
tests/test_zigbee_util.py
zigpy/__init__.py
zigpy/endpoint.py
zigpy/util.py
zigpy/zcl/__init__.py

0.20.2 Release

---

tox.ini
zigpy/util.py
zigpy/zcl/clusters/general.py

Catch duplicate TSN exception for OTA

Catch duplicate TSN exception for OTA

---

tox.ini
zigpy/__init__.py
zigpy/util.py
zigpy/zcl/clusters/general.py

0.20.3 Release

---

tests/test_zcl_clusters.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py

Update signature for `handle_cluster_general_request()` method of the `Time` cluster.

Update signature for handle_cluster_general_request of Time cluster

---

README.md
tests/test_zcl_clusters.py
zigpy/__init__.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py

0.20.4 Release

---

tests/test_quirks.py
tests/test_quirks_registry.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py
zigpy/typing.py

Drop support for old style of quirk signature.

Drop support for old style of quirks signature

---

tests/test_zcl.py
zigpy/typing.py
zigpy/zcl/__init__.py

__setitem__ will schedule an attribute write command, which if completed successfuly would update the cached value.

Access attribute cached value via __getitem__

---

tests/test_quirks.py
tests/test_quirks_registry.py
tests/test_types.py
tests/test_zcl.py
zigpy/__init__.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py
zigpy/types/struct.py
zigpy/typing.py
zigpy/zcl/__init__.py

0.21.0 Release

---

tests/test_quirks.py
zigpy/zcl/__init__.py

Refactor Cluster.read_attributes() signature

---

tests/test_quirks.py

Update quirks coverage

---

zigpy/zcl/__init__.py

Fix CustomCluster manufacturer_attributes

---

zigpy/__init__.py
zigpy/zcl/__init__.py

0.22.1 Release

---

CONTRIBUTING.md

Update CONTRIBUTING.md with zigpy API how-to info from @pipiche38 to get that part started too. 
Copied straight from his https://github.com/pipiche38/Domoticz-Zigpy/blob/master/zigpy_api.md
@pipiche38 hope that you do not take offence if I copied this, if so please post to in the PR for this.

Update CONTRIBUTING.md with zigpy API info from pipiche38

---

README.md

Update README.md with related projects as references because I think it is a good idea to let new zigpy developers (and users) know of these in case they would like to help out, reuse the code, or utilize them for related projects.

Update README.md with more related related projects for reference

---

.pre-commit-config.yaml
tests/test_group.py
tests/test_quirks.py
tests/test_zcl.py
tox.ini
zigpy/quirks/__init__.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/foundation.py

Update to black==20.8b1

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md
setup.py
tests/test_group.py
tests/test_ota_provider.py
tests/test_quirks.py
tests/test_struct.py
tests/test_types.py
tests/test_zcl.py
tests/test_zcl_foundation.py
tests/test_zdo_types.py
tox.ini
zigpy/__init__.py
zigpy/ota/image.py
zigpy/ota/provider.py
zigpy/quirks/__init__.py
zigpy/types/basic.py
zigpy/types/named.py
zigpy/types/struct.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/clusters/lightlink.py
zigpy/zcl/clusters/protocol.py
zigpy/zcl/clusters/security.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

0.23.0 Release

---

tests/test_zcl_foundation.py
zigpy/zcl/foundation.py

Fix ZCL Structure data type

---

README.md
tests/test_zcl_foundation.py
zigpy/__init__.py
zigpy/zcl/foundation.py

0.23.1 Release

---

tests/test_struct.py
zigpy/types/struct.py

Bugfix for `t.Neighbor` struct that had an uppercase `LQI` field that was being mistaken for a constant.
All `t.Struct` attributes must now be:
- constants that are `_underscore_prefixed` or `UPPERCASE` (optionally annotated)
- methods, functions, or properties/setters
- annotated variables
- or have a value of `t.StructField()`

Fix `t.Struct` skipping uppercase fields

---

README.md
tests/test_struct.py
zigpy/__init__.py
zigpy/types/struct.py

0.23.2 Release

---

zigpy/device.py

Makes get_signature method returning more device informations such as 
Model Id, 
Manufacturer Name/Code, 
ProfileID  
DeviceId
This will ease getting essential information on the application side.
PS/ I'm thinking to return battery level when the device has a battery component.

Enhance get_signature

---

tests/test_ota_provider.py
zigpy/ota/provider.py

Handle OTA firmware list download failures.

Handle OTA firmware list download failures

---

tests/test_ota_provider.py
zigpy/__init__.py
zigpy/ota/provider.py

0.24.1 Release

---

tests/test_zdo_types.py
zigpy/appdb.py
zigpy/zdo/types.py

Collapse Neighbor and _NeighborStruct classes into a single one.

Collapse Neighbor and _NeighborStruct classes into a single one

---

tests/test_zdo_types.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/zdo/types.py

0.24.2 Release

---

tests/test_ota.py
tests/test_ota_validators.py
zigpy/__init__.py
zigpy/ota/__init__.py
zigpy/ota/validators.py

0.24.3 Release

---

.travis.yml

Run travis on additional python versions

Run travis on additional python versions

---

README.md

Update README.md added Zigzag project under related projects for reference

Update README.md added Zigzag project under related projects reference

---

.travis.yml
README.md
tests/test_appdb.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/device.py
zigpy/endpoint.py

0.26.0 Release

---

tests/test_ota_validators.py
zigpy/ota/validators.py

Hue GBL firmware images contain unexpected null bytes as padding and thus fail validation. This fix relaxes the constraint.
Below are the validation results after this patch for every known OTA file:
```
Not an OTA image: ConnectedLamp-Atmel_0104_5.130.1.30000_0012.sbl-ota, Data is too short for SubElement
Not an OTA image: LivCol_0103_5.127.1.26581_0012.sbl-ota, Data is too short for SubElement
Not an OTA image: LivingColors-Target_0108_5.130.1.30000_0012.sbl-ota, Data is too short for SubElement
Not an OTA image: ModuLum-ATmega_010B_5.130.1.30000_0012.sbl-ota, Data is too short for SubElement
Not an OTA image: Sensor-ATmega_6.1.1.27575_0012.sbl-ota, Data is too short for SubElement
Not an OTA image: Switch-ATmega_6.1.1.28573_0012.sbl-ota, Data is too short for SubElement
Not an OTA …
```

Allow null padding bytes in GBL files (fixes #525)

---

zigpy/zcl/__init__.py

Some commands might also benefit from retying.

add 'tries' to 'Cluster.command'

---

.github/workflows/ci.yml
requirements_test.txt

Migrate from Travis.io to GH Actions

Use GitHub Actions for  builds

---

.github/workflows/ci.yml
tests/test_zdo.py

Add Python 3.9 to test matrix.

Add Python 3.9 to test matrix

---

.github/workflows/ci.yml
.github/workflows/matchers/flake8.json
.github/workflows/matchers/python.json
.pre-commit-config.yaml
.travis.yml
README.md
requirements_test.txt
setup.py
tests/test_appdb.py
tests/test_device.py
tests/test_ota_validators.py
tests/test_zdo.py
tox.ini
zigpy/__init__.py
zigpy/appdb.py
zigpy/application.py
zigpy/device.py
zigpy/ota/validators.py
zigpy/zcl/__init__.py

0.27.0 Release

---

README.md

Update README.md with new URL link to Zigzag
https://github.com/Samantha-uk/zigzag-v1

Update README.md with new URL link to Zigzag

---

.github/workflows/ci.yml
.github/workflows/release-management.yml
README.md
setup.py
tests/test_zdo.py
zigpy/__init__.py

0.27.1 Release

---

tests/test_quirks.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py

Use constants for quirk signature.

Use consts for quirks

---

tests/test_appdb.py
tests/test_application.py
tests/test_quirks.py
zigpy/__init__.py
zigpy/application.py
zigpy/device.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py

0.28.0 Release

---

zigpy/quirks/__init__.py

Fix `zigpy.quirks.get_model_quirks()`

Let defaultdict do it's job when retrieving a list of quirks for specific model

---

zigpy/__init__.py
zigpy/quirks/__init__.py

0.28.1 Release

---

README.md
tests/test_quirks.py
zigpy/__init__.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py

0.28.2 Release

---

README.md

Update README.md with adding ZigCoHTTP as a related project for reference.
Also removed duplicate listing of ZHA Custom Radios under related projects.

Update README.md with adding ZigCoHTTP to related projects

---

.github/workflows/ci.yml
.github/workflows/matchers/codespell.json

Make codespell part of CI

---

.github/workflows/ci.yml
README.md
tests/test_appdb.py
tests/test_quirks.py
tests/test_quirks_registry.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/quirks/registry.py

0.30.0 Release

---

README.md

Update README.md with some info about OTA updates

Update README.md with some info about OTA updates

---

README.md
tests/test_zcl.py
zigpy/__init__.py
zigpy/types/named.py

0.30.1 Release

---

.github/workflows/publish-to-pypi.yml

Update pypi package publishing GH Acitons

Update workflow actions for package publishing

---

.github/workflows/publish-to-pypi.yml
tests/test_quirks.py
tests/test_quirks_registry.py
zigpy/__init__.py
zigpy/quirks/registry.py

0.31.0 Release

---

zigpy/zcl/__init__.py

Implement a handler for sending a default response.

Helper for sending a default response

---

tests/test_endpoint.py
tests/test_zcl.py
tests/test_zcl_clusters.py
zigpy/__init__.py
zigpy/endpoint.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py

0.32.0 Release

---

tests/test_struct.py
tests/test_zcl_clusters.py
tests/test_zdo_types.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/application.py
zigpy/device.py
zigpy/endpoint.py
zigpy/ota/image.py
zigpy/types/named.py
zigpy/types/struct.py
zigpy/util.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/lightlink.py
zigpy/zcl/clusters/measurement.py
zigpy/zcl/clusters/protocol.py
zigpy/zcl/clusters/security.py
zigpy/zcl/foundation.py
zigpy/zdo/types.py

0.33.0 Release

---

.github/workflows/publish-to-pypi.yml
tests/test_endpoint.py
zigpy/__init__.py
zigpy/endpoint.py
zigpy/zcl/__init__.py

0.35.0 Release

---

tests/test_appdb_migration.py
tests/test_ota_validators.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/ota/validators.py

0.35.1 Release

---

tests/test_application.py
zigpy/application.py

Retrieve device by IEEE if NWK matches the one of the controller itself.

Refactor ApplicationController.get_device()

---

tests/test_application.py
zigpy/__init__.py
zigpy/application.py

0.35.2 Release

---

tests/databases/simple_v5.sql
tests/test_appdb.py
tests/test_appdb_migration.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/appdb_schemas/schema_v6.sql

0.36.1 Release

---

tests/test_application.py
tests/test_topology.py
zigpy/__init__.py
zigpy/application.py
zigpy/device.py
zigpy/topology.py

0.36.2 Release

---

tests/conftest.py
tests/test_app_state.py
tests/test_application.py
tests/test_device.py
tests/test_group.py
tests/test_quirks.py
zigpy/__init__.py
zigpy/application.py
zigpy/state.py
zigpy/zcl/clusters/lighting.py

0.37.0 Release

---

zigpy/state.py

Fix key class

---

zigpy/__init__.py
zigpy/state.py

0.37.1 Release

---

tests/test_zcl_clusters.py
zigpy/zcl/clusters/security.py

Send default response to IAS zone status change notification command

Send default response to IAS zone status change notification

---

tests/test_ota_provider.py
zigpy/__init__.py
zigpy/ota/provider.py

0.37.2 Release

---

.github/workflows/stale.yml
tests/test_appdb.py
tests/test_appdb_migration.py
tests/test_ota_provider.py
tests/test_zcl.py
tests/test_zcl_clusters.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/appdb_schemas/schema_v7.sql
zigpy/ota/provider.py
zigpy/state.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/security.py

0.38.0 Release

---

zigpy/__init__.py
zigpy/zcl/clusters/measurement.py

0.41.0 Release

---

tests/test_zdo.py
zigpy/__init__.py
zigpy/zcl/__init__.py
zigpy/zdo/__init__.py

0.42.0 Release

---

README.md

Following #839 the readme should be updated.
Also I corrected a couple of grammatical errors and reworded it a bit.  Hope that's ok!

Update for SALUS OTA support + minor rewording

---

.github/workflows/ci.yml
requirements_test.txt
tests/test_appdb.py
tests/test_appdb_migration.py
tests/test_appdb_pysqlite.py
zigpy/appdb.py

Enforce minimum SQLite version and use `UPSERT` syntax

---

README.md
tests/test_zcl.py
zigpy/zcl/__init__.py

Implement #873 
Enables writing attributes that are not predefined.
Similar to read_attributes_raw

#873 Add write_attributes_raw method

---

tests/test_application.py
tests/test_zdo.py
zigpy/application.py
zigpy/zdo/__init__.py

Fixes #831 
Thanks to @mattwest and @puddly  for identifying the issue and fix.

Use correct values for ZDO leave request flags

---

tests/test_endpoint.py
zigpy/endpoint.py

Handle timeouts again when reading two attributes during device init

---

tests/test_quirks.py
tests/test_zcl_foundation.py
zigpy/zcl/foundation.py

Allow disabling the automatic manufacturer ID override in quirks

---

tests/test_ota_image.py
zigpy/ota/image.py

Parse Legrand OTA images

---

zigpy/zcl/__init__.py

Change warning to debug for unknown clusters

---

zigpy/ota/OTA_URLs.md

Create OTA_URLs.md to collect external URLs

Create OTA_URLs.md to collect external URLs

---

tests/test_zcl.py
zigpy/zcl/__init__.py

Persist attribute writes in the database

---

zigpy/ota/OTA_URLs.md

Update OTA_URLs.md with some Philips Hue URLs got from https://github.com/Koenkk/zigbee-herdsman-converters/pull/4124

Update OTA_URLs.md Philips Hue URLs

---

.github/workflows/ci.yml
setup.py
tests/async_mock.py
tests/test_appdb.py
tests/test_appdb_migration.py
tests/test_device.py
tests/test_ota_provider.py
tests/test_struct.py
tests/test_zcl.py
tests/test_zcl_clusters.py
tests/test_zigbee_util.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/appdb_schemas/schema_v8.sql
zigpy/application.py
zigpy/device.py
zigpy/ota/OTA_URLs.md
zigpy/ota/provider.py
zigpy/types/named.py
zigpy/types/struct.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py

0.45.0 Release

---

zigpy/ota/OTA_URLs.md

Update OTA_URLs.md with Inovelli URLs for reference.

Update OTA_URLs.md with Inovelli URLs

---

.github/workflows/ci.yml
CONTRIBUTING.md
README.md
tests/async_mock.py
tests/conftest.py
tests/test_application.py
tests/test_device.py
tests/test_zcl.py
tests/test_zigbee_util.py
zigpy/__init__.py
zigpy/application.py
zigpy/ota/provider.py

0.47.2 Release

---

.github/workflows/ci.yml
setup.py
tests/test_application.py
tests/test_device.py
tests/test_quirks.py
tests/test_zigbee_util.py
zigpy/appdb.py
zigpy/device.py

Python 3.7 will be end-of-life in 11 months and I don't know of any project depending on Zigpy's Python 3.7 support.

Drop support for Python 3.7

---

.github/workflows/ci.yml
setup.py
tests/test_appdb.py
tests/test_appdb_migration.py
tests/test_application.py
tests/test_device.py
tests/test_quirks.py
tests/test_zigbee_util.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/device.py

0.47.3 Release

---

zigpy/__init__.py
zigpy/application.py

0.49.1 Release

---

zigpy/__init__.py
zigpy/application.py

0.50.0 Release

---

setup.py
zigpy/__init__.py

0.50.1 Release

---

requirements_test.txt
tests/test_appdb.py
zigpy/__init__.py
zigpy/appdb.py

0.50.2 Release

---

README.md

Update README.md Zigbee OTA summery to also mention Inovelli and clarify that support for additional OTA provider download sources can be added.

Update README.md Zigbee OTA summery

---

README.md

Update README.md to mention OTA for "SONOFF/ITEAD" as per https://github.com/zigpy/zigpy/pull/1040 and https://github.com/zigpy/zigpy/issues/987
PS: ITEAD Intelligent Systems / ITEAD Studio is the manufacturer and SONOFF is one of their brands:
https://itead.cc
https://sonoff.tech

Update README.md to mention OTA for SONOFF/ITEAD

---

README.md
tests/test_quirks.py
tests/test_types.py
zigpy/__init__.py
zigpy/quirks/__init__.py
zigpy/types/basic.py
zigpy/util.py
zigpy/zcl/clusters/general.py

0.51.1 Release

---

tests/test_application.py
zigpy/__init__.py
zigpy/application.py

0.51.2 Release

---

tests/test_struct.py
tests/test_zcl.py
zigpy/__init__.py
zigpy/types/struct.py
zigpy/zcl/__init__.py

0.51.3 Release

---

zigpy/ota/OTA_URLs.md

Correct error in documentation

Correct documentation: Salus is not hue

---

.github/workflows/ci.yml
tests/test_device.py
tests/test_zcl_foundation.py
tests/test_zdo.py
zigpy/__init__.py
zigpy/device.py
zigpy/ota/OTA_URLs.md
zigpy/types/basic.py
zigpy/zcl/clusters/closures.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/homeautomation.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/clusters/lighting.py
zigpy/zcl/clusters/measurement.py
zigpy/zcl/clusters/protocol.py
zigpy/zcl/clusters/security.py
zigpy/zcl/clusters/smartenergy.py
zigpy/zcl/foundation.py
zigpy/zdo/__init__.py

0.51.4 Release

---

tests/test_application.py
zigpy/__init__.py
zigpy/application.py

0.51.5 Release

---

tests/test_ota_image.py
zigpy/ota/image.py

The OTA images from https://tr-zha.s3.amazonaws.com/firmware.json are not in any known OTA format and contain a 152 byte prefix. This PR identifies them and strips the header, allowing zigpy to utilize the OTA images.
All OTA images have the same manufacturer ID (4659/0x1233) but many images are indistinguishable from one another despite targeting seemingly different hardware.
```Python
3RSS007Z_0_010_000_20190218_054240.bin    (image_type=20841, file_version=10, header_string='3RSS007Z-UNENCRYPTED-80205JN5169')
3RSS007Z_2_010_000_20200511_085155.hub    (image_type=20841, file_version=10, header_string='3RSS007Z-UNENCRYPTED-80205JN5169')
3RSS008Z_3_010_000_20190801_080629.hub    (image_type=20841, file_version=10, header_string='3RSS008Z-JN5169-HW03-UNENCRYPTED') …
```

Parse the Third Reality OTA image file format

---

zigpy/ota/OTA_URLs.md

Update OTA_URLs.md with Sonoff OTA Provider URL as per https://github.com/zigpy/zigpy/pull/1040

Update OTA_URLs.md with Sonoff OTA Provider URL

---

zigpy/ota/OTA_URLs.md

Just for reference also 1Add URL for Third Reality (3reality) OTA provider to OTA_URLs.md

Add URL for Third Reality (3reality) OTA provider to OTA_URLs.md

---

.pre-commit-config.yaml

https://github.com/PyCQA/flake8/issues/1737

Fix pre-commit failing to install flake8

---

tests/test_zcl_foundation.py
zigpy/zcl/foundation.py

So two instances can be compared for equality normally.

Make `TypeValue` a dataclass so it implements comparison operators

---

tests/test_config.py
zigpy/config/__init__.py
zigpy/config/validators.py
zigpy/ota/OTA_URLs.md
zigpy/ota/provider.py

Addresses https://github.com/zigpy/zigpy/pull/1104#issuecomment-1329495639

Deprecate the IKEA OTA test feed

---

setup.py
tests/test_topology.py
zigpy/__init__.py
zigpy/appdb_schemas/__init__.py
zigpy/topology.py

0.52.1 Release

---

tests/ota_providers/test_ota_provider_thirdreality.py
zigpy/__init__.py
zigpy/ota/provider.py

0.52.2 Release

---

setup.cfg
tests/conftest.py
tests/test_appdb.py
tests/test_appdb_migration.py
tests/test_application.py
tests/test_backups.py
tests/test_topology.py
tests/test_zdo.py
zigpy/__init__.py
zigpy/application.py

0.52.3 Release

---

.coveragerc
CONTRIBUTING.md
setup.cfg
tests/test_appdb_migration.py
tests/test_application.py
tests/test_listeners.py
tests/test_ota_validators.py
tests/test_struct.py
tests/test_types.py
tests/test_zcl_foundation.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/application.py
zigpy/device.py
zigpy/exceptions.py
zigpy/listeners.py
zigpy/ota/validators.py
zigpy/types/basic.py
zigpy/types/struct.py
zigpy/zcl/clusters/smartenergy.py
zigpy/zcl/foundation.py

0.53.0 Release

---

.github/workflows/ci.yml
.github/workflows/matchers/ruff.json
.pre-commit-config.yaml
requirements_test.txt
ruff.toml
tests/test_application.py
tests/test_zcl_foundation.py
zigpy/__init__.py
zigpy/appdb.py
zigpy/application.py
zigpy/backups.py
zigpy/device.py
zigpy/endpoint.py
zigpy/listeners.py
zigpy/ota/image.py
zigpy/ota/validators.py
zigpy/quirks/registry.py
zigpy/serial.py
zigpy/types/basic.py
zigpy/types/named.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zcl/clusters/general.py
zigpy/zcl/clusters/hvac.py
zigpy/zcl/clusters/lighting.py
zigpy/zcl/clusters/measurement.py
zigpy/zcl/clusters/security.py
zigpy/zcl/foundation.py

0.53.3 Release

---

setup.cfg
setup.py
tests/test_application.py
tests/test_quirks.py
zigpy/__init__.py
zigpy/appdb_schemas/__init__.py
zigpy/application.py
zigpy/config/__init__.py
zigpy/config/defaults.py
zigpy/const.py
zigpy/endpoint.py
zigpy/ota/__init__.py
zigpy/ota/image.py
zigpy/ota/provider.py
zigpy/profiles/__init__.py
zigpy/profiles/zha.py
zigpy/profiles/zll.py
zigpy/quirks/__init__.py
zigpy/quirks/registry.py
zigpy/state.py
zigpy/topology.py
zigpy/types/__init__.py
zigpy/types/named.py
zigpy/types/struct.py
zigpy/util.py
zigpy/zcl/__init__.py
zigpy/zcl/foundation.py

0.55.0 Release

---

tests/test_topology.py
zigpy/__init__.py
zigpy/topology.py

0.56.1 Release
